// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/com/example/proyecto1_compi1_ps26/domain/analyzers/saved_pkm/LexerPKM.flex

// IMPORTS
package com.example.proyecto1_compi1_ps26.domain.analyzers.saved_pkm;

import java_cup.runtime.*;
import com.example.proyecto1_compi1_ps26.domain.analyzers.saved_pkm.symPKM;

import java.util.ArrayList;

import com.example.proyecto1_compi1_ps26.domain.entities.ErrorReport;


@SuppressWarnings("fallthrough")
public class LexerPKM implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int TEXT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\5"+
    "\1\0\1\6\1\7\1\0\1\10\2\0\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\12\21\1\22"+
    "\1\0\1\23\1\24\1\25\2\0\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\37\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\3\0"+
    "\1\57\1\60\1\0\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\37\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\61\1\0\1\62"+
    "\7\0\1\3\252\0\2\63\115\0\1\64\u01a8\0\2\3"+
    "\u0100\0\1\65\325\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\3\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\23\21\1\22\1\1\1\23\1\24\1\1"+
    "\1\25\2\26\1\27\2\0\1\30\1\0\20\21\1\0"+
    "\11\21\1\0\6\21\3\0\1\26\1\31\2\0\1\32"+
    "\1\21\1\0\11\21\1\0\11\21\1\0\4\21\1\33"+
    "\3\21\1\34\1\21\1\34\5\21\1\0\1\21\4\0"+
    "\1\35\1\36\1\21\1\0\2\21\1\0\1\21\1\37"+
    "\4\21\1\0\2\21\2\0\2\21\1\40\4\21\1\41"+
    "\1\21\1\0\2\42\1\43\1\21\1\44\2\21\1\0"+
    "\4\21\1\45\3\21\1\0\1\21\4\0\1\21\1\0"+
    "\2\21\1\0\2\46\1\21\1\47\2\21\1\0\2\21"+
    "\2\0\3\21\1\50\1\0\1\51\1\21\1\0\1\21"+
    "\1\0\2\21\1\0\1\21\1\0\1\21\1\52\1\53"+
    "\1\0\2\21\1\0\2\54\1\21\1\0\1\52\1\0"+
    "\1\21\1\0\1\55\1\21\1\0\1\56\2\21\1\0"+
    "\1\21\1\0\1\21\1\0\1\57\1\60\1\21\1\0"+
    "\1\21\1\0\1\21\1\0\1\61\1\21\1\0\1\21"+
    "\1\0\1\21\1\62\2\0\1\21\1\0\1\63\1\0"+
    "\1\62\1\35\1\21\1\0\1\21\1\0\1\64\2\65"+
    "\1\21\1\0\1\21\1\0\1\66\1\0\1\21\1\0"+
    "\1\21\1\0\1\21\1\0\2\67\1\21\3\0\1\21"+
    "\1\0\2\70\1\21\1\0\1\21\1\0\1\21\2\0"+
    "\1\21\1\0\2\71\1\21\1\0\1\21\3\0\2\72"+
    "\1\21\1\0\1\21\1\0\1\21\2\0\1\21\1\0"+
    "\2\73\1\21\1\0\2\74\1\75\1\0\1\21\1\0"+
    "\1\21\1\0\1\21\2\0\2\76\2\77\3\0\2\100"+
    "\1\21\1\0\1\101\3\0\2\102\13\0\1\103\4\0"+
    "\1\104\1\105";

  private static int [] zzUnpackAction() {
    int [] result = new int[375];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\154\0\242\0\330\0\154\0\u010e"+
    "\0\154\0\154\0\154\0\154\0\154\0\154\0\u0144\0\154"+
    "\0\u017a\0\154\0\154\0\154\0\154\0\u01b0\0\u01e6\0\u021c"+
    "\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc"+
    "\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da\0\u0510\0\u0546\0\u057c"+
    "\0\154\0\u05b2\0\154\0\154\0\u05e8\0\154\0\u061e\0\u0654"+
    "\0\154\0\u068a\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798\0\u07ce"+
    "\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948\0\u097e"+
    "\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e"+
    "\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde"+
    "\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec\0\u0e22\0\u0e58\0\u0e8e"+
    "\0\u0ec4\0\154\0\154\0\u0efa\0\u0f30\0\u072c\0\u0f66\0\u0f9c"+
    "\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u10e0\0\u1116\0\u114c"+
    "\0\u1182\0\u11b8\0\u11ee\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12fc"+
    "\0\u1332\0\u1368\0\u139e\0\u13d4\0\u140a\0\u1440\0\u1476\0\u14ac"+
    "\0\u0360\0\u14e2\0\u1518\0\u154e\0\u0360\0\u1584\0\154\0\u15ba"+
    "\0\u15f0\0\u1626\0\u165c\0\u1692\0\u16c8\0\u16fe\0\u1734\0\u176a"+
    "\0\u17a0\0\u17d6\0\u180c\0\u0f30\0\u1842\0\u1878\0\u18ae\0\u18e4"+
    "\0\u191a\0\u1950\0\u0360\0\u1986\0\u19bc\0\u19f2\0\u1a28\0\u1a5e"+
    "\0\u1a94\0\u1aca\0\u1b00\0\u1b36\0\u1b6c\0\u1ba2\0\u0360\0\u1bd8"+
    "\0\u1c0e\0\u1c44\0\u1c7a\0\u0360\0\u1cb0\0\u1ce6\0\u0360\0\154"+
    "\0\u0360\0\u1d1c\0\u0360\0\u1d52\0\u1d88\0\u1dbe\0\u1df4\0\u1e2a"+
    "\0\u1e60\0\u1e96\0\u1ecc\0\u1f02\0\u1f38\0\u1f6e\0\u1fa4\0\u1fda"+
    "\0\u2010\0\u2046\0\u207c\0\u20b2\0\u20e8\0\u211e\0\u2154\0\u218a"+
    "\0\u21c0\0\u0360\0\154\0\u21f6\0\u0360\0\u222c\0\u2262\0\u2298"+
    "\0\u22ce\0\u2304\0\u233a\0\u2370\0\u23a6\0\u23dc\0\u2412\0\u0360"+
    "\0\u2448\0\u0360\0\u247e\0\u24b4\0\u24ea\0\u2520\0\u2556\0\u258c"+
    "\0\u25c2\0\u25f8\0\u262e\0\u2664\0\u0360\0\u0360\0\u269a\0\u26d0"+
    "\0\u2706\0\u273c\0\u0360\0\154\0\u2772\0\u27a8\0\154\0\u27de"+
    "\0\u2814\0\u284a\0\u0360\0\u2880\0\u28b6\0\u0360\0\u28ec\0\u2922"+
    "\0\u2958\0\u298e\0\u29c4\0\u29fa\0\u2a30\0\u0360\0\u0360\0\u2a66"+
    "\0\u2a9c\0\u2ad2\0\u2b08\0\u2b3e\0\u2b74\0\u0360\0\u2baa\0\u2be0"+
    "\0\u2c16\0\u2c4c\0\u2c82\0\u0360\0\u2cb8\0\u2cee\0\u2d24\0\u2d5a"+
    "\0\u0360\0\u2d90\0\154\0\154\0\u2dc6\0\u2dfc\0\u2e32\0\u2e68"+
    "\0\u0360\0\u0360\0\154\0\u2e9e\0\u2ed4\0\u2f0a\0\u2f40\0\u0360"+
    "\0\u2f76\0\u2fac\0\u2fe2\0\u3018\0\u304e\0\u3084\0\u30ba\0\u0360"+
    "\0\154\0\u30f0\0\u3126\0\u315c\0\u3192\0\u31c8\0\u31fe\0\u0360"+
    "\0\154\0\u3234\0\u326a\0\u32a0\0\u32d6\0\u330c\0\u3342\0\u3378"+
    "\0\u33ae\0\u33e4\0\u341a\0\u3450\0\u3486\0\u34bc\0\u34f2\0\u3528"+
    "\0\u355e\0\u3594\0\u0360\0\154\0\u35ca\0\u3600\0\u3636\0\u366c"+
    "\0\u36a2\0\u36d8\0\u370e\0\u3744\0\u377a\0\u0360\0\154\0\u37b0"+
    "\0\u37e6\0\u0360\0\154\0\154\0\u381c\0\u3852\0\u3888\0\u38be"+
    "\0\u38f4\0\u392a\0\u3960\0\u3996\0\u0360\0\154\0\u0360\0\154"+
    "\0\u39cc\0\u3a02\0\u3a38\0\u0360\0\154\0\u3a6e\0\u3aa4\0\154"+
    "\0\u3ada\0\u3b10\0\u3b46\0\u0360\0\154\0\u3b7c\0\u3bb2\0\u3be8"+
    "\0\u3c1e\0\u3c54\0\u3c8a\0\u3cc0\0\u3cf6\0\u3d2c\0\u3d62\0\u3d98"+
    "\0\154\0\u3dce\0\u3e04\0\u3e3a\0\u3e70\0\154\0\154";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[375];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\0\1\6\1\4\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\3"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\3\36\1\37"+
    "\1\40\1\36\1\41\1\42\1\43\1\44\1\45\1\36"+
    "\1\46\1\47\1\36\1\50\1\36\1\51\1\52\1\53"+
    "\1\54\1\3\1\55\1\3\2\56\1\57\1\56\1\60"+
    "\1\56\1\61\57\56\72\0\1\4\63\0\1\4\72\0"+
    "\1\62\11\0\1\63\4\0\6\63\53\0\1\64\63\0"+
    "\1\65\1\0\1\21\65\0\1\36\4\0\1\36\1\66"+
    "\21\36\1\67\5\36\1\0\1\36\26\0\1\36\4\0"+
    "\1\70\12\36\1\71\2\36\1\72\12\36\1\0\1\36"+
    "\26\0\1\36\4\0\16\36\1\73\4\36\1\74\5\36"+
    "\1\0\1\36\26\0\1\36\4\0\4\36\1\75\11\36"+
    "\1\76\1\36\1\77\10\36\1\0\1\36\26\0\1\36"+
    "\4\0\13\36\1\100\15\36\1\0\1\36\26\0\1\36"+
    "\4\0\4\36\1\101\11\36\1\102\12\36\1\0\1\36"+
    "\26\0\1\36\4\0\20\36\1\103\10\36\1\0\1\36"+
    "\26\0\1\36\4\0\16\36\1\104\12\36\1\0\1\36"+
    "\26\0\1\36\4\0\31\36\1\0\1\36\26\0\1\36"+
    "\4\0\10\36\1\105\20\36\1\0\1\36\2\0\1\106"+
    "\23\0\1\36\4\0\16\36\1\107\4\36\1\110\5\36"+
    "\1\0\1\36\26\0\1\36\4\0\17\36\1\111\11\36"+
    "\1\0\1\36\26\0\1\36\4\0\23\36\1\112\5\36"+
    "\1\0\1\36\26\0\1\36\4\0\4\36\1\113\24\36"+
    "\1\0\1\36\26\0\1\36\4\0\1\114\3\36\1\115"+
    "\5\36\1\116\7\36\1\117\6\36\1\0\1\36\4\0"+
    "\1\120\21\0\1\36\4\0\1\121\3\36\1\122\11\36"+
    "\1\123\12\36\1\0\1\36\26\0\1\36\4\0\4\36"+
    "\1\124\24\36\1\0\1\36\26\0\1\36\4\0\7\36"+
    "\1\125\21\36\1\0\1\36\26\0\1\36\4\0\4\36"+
    "\1\126\24\36\1\0\1\36\33\0\31\36\35\0\1\127"+
    "\3\0\1\130\5\0\1\120\7\0\1\131\14\0\1\120"+
    "\4\0\1\132\63\0\1\132\72\0\1\133\77\0\1\134"+
    "\4\0\6\134\51\0\1\135\1\0\1\64\65\0\1\136"+
    "\65\0\1\36\4\0\10\36\1\137\20\36\1\0\1\36"+
    "\2\0\1\140\23\0\1\36\4\0\22\36\1\141\6\36"+
    "\1\0\1\36\26\0\1\36\4\0\2\36\1\142\26\36"+
    "\1\0\1\36\26\0\1\36\4\0\1\143\22\36\1\144"+
    "\5\36\1\0\1\36\26\0\1\36\4\0\20\36\1\145"+
    "\10\36\1\0\1\36\26\0\1\36\4\0\13\36\1\146"+
    "\1\36\1\147\13\36\1\0\1\36\26\0\1\36\4\0"+
    "\20\36\1\150\10\36\1\0\1\36\26\0\1\36\4\0"+
    "\21\36\1\151\7\36\1\0\1\36\3\0\1\152\22\0"+
    "\1\36\4\0\22\36\1\153\1\154\5\36\1\0\1\36"+
    "\26\0\1\36\4\0\16\36\1\155\12\36\1\0\1\36"+
    "\26\0\1\36\4\0\4\36\1\156\24\36\1\0\1\36"+
    "\26\0\1\36\4\0\2\36\1\157\26\36\1\0\1\36"+
    "\26\0\1\36\4\0\15\36\1\160\13\36\1\0\1\36"+
    "\26\0\1\36\4\0\4\36\1\161\24\36\1\0\1\36"+
    "\26\0\1\36\4\0\20\36\1\162\10\36\1\0\1\36"+
    "\26\0\1\36\4\0\15\36\1\163\13\36\1\0\1\36"+
    "\50\0\1\164\43\0\1\36\4\0\15\36\1\165\13\36"+
    "\1\0\1\36\26\0\1\36\4\0\13\36\1\166\15\36"+
    "\1\0\1\36\26\0\1\36\4\0\4\36\1\167\24\36"+
    "\1\0\1\36\26\0\1\36\4\0\20\36\1\170\10\36"+
    "\1\0\1\36\26\0\1\36\4\0\3\36\1\171\25\36"+
    "\1\0\1\36\26\0\1\36\4\0\15\36\1\172\13\36"+
    "\1\0\1\36\26\0\1\36\4\0\2\36\1\173\10\36"+
    "\1\174\15\36\1\0\1\36\26\0\1\36\4\0\27\36"+
    "\1\175\1\36\1\0\1\36\26\0\1\36\4\0\27\36"+
    "\1\176\1\36\1\0\1\36\62\0\1\177\31\0\1\36"+
    "\4\0\1\36\1\200\27\36\1\0\1\36\26\0\1\36"+
    "\4\0\26\36\1\201\2\36\1\0\1\36\26\0\1\36"+
    "\4\0\22\36\1\202\6\36\1\0\1\36\26\0\1\36"+
    "\4\0\20\36\1\203\10\36\1\0\1\36\26\0\1\36"+
    "\4\0\10\36\1\204\20\36\1\0\1\36\2\0\1\205"+
    "\23\0\1\36\4\0\13\36\1\206\15\36\1\0\1\36"+
    "\50\0\1\207\52\0\1\210\10\0\1\211\101\0\1\212"+
    "\31\0\1\213\4\0\6\213\53\0\1\214\65\0\1\36"+
    "\4\0\4\36\1\215\24\36\1\0\1\36\37\0\1\216"+
    "\54\0\1\36\4\0\7\36\1\217\21\36\1\0\1\36"+
    "\26\0\1\36\4\0\12\36\1\220\16\36\1\0\1\36"+
    "\4\0\1\221\21\0\1\36\4\0\2\36\1\222\26\36"+
    "\1\0\1\36\26\0\1\36\4\0\4\36\1\223\24\36"+
    "\1\0\1\36\26\0\1\36\4\0\3\36\1\224\25\36"+
    "\1\0\1\36\26\0\1\36\4\0\16\36\1\225\12\36"+
    "\1\0\1\36\26\0\1\36\4\0\22\36\1\226\6\36"+
    "\1\0\1\36\26\0\1\36\4\0\21\36\1\227\7\36"+
    "\1\0\1\36\3\0\1\230\22\0\1\36\4\0\2\36"+
    "\1\231\14\36\1\232\11\36\1\0\1\36\35\0\1\233"+
    "\14\0\1\234\41\0\1\36\4\0\22\36\1\235\6\36"+
    "\1\0\1\36\26\0\1\36\4\0\1\36\1\236\27\36"+
    "\1\0\1\36\26\0\1\36\4\0\17\36\1\237\11\36"+
    "\1\0\1\36\26\0\1\36\4\0\14\36\1\240\14\36"+
    "\1\0\1\36\26\0\1\36\4\0\7\36\1\241\21\36"+
    "\1\0\1\36\26\0\1\36\4\0\22\36\1\242\6\36"+
    "\1\0\1\36\26\0\1\36\4\0\4\36\1\243\24\36"+
    "\1\0\1\36\26\0\1\36\4\0\1\244\7\36\1\245"+
    "\20\36\1\0\1\36\2\0\1\246\23\0\1\36\4\0"+
    "\4\36\1\247\24\36\1\0\1\36\37\0\1\250\54\0"+
    "\1\36\4\0\16\36\1\251\12\36\1\0\1\36\26\0"+
    "\1\36\4\0\22\36\1\252\6\36\1\0\1\36\26\0"+
    "\1\36\4\0\15\36\1\253\13\36\1\0\1\36\26\0"+
    "\1\36\4\0\17\36\1\254\11\36\1\0\1\36\26\0"+
    "\1\36\4\0\21\36\1\255\7\36\1\0\1\36\3\0"+
    "\1\256\22\0\1\36\4\0\22\36\1\257\6\36\1\0"+
    "\1\36\26\0\1\36\4\0\4\36\1\260\24\36\1\0"+
    "\1\36\26\0\1\36\4\0\13\36\1\261\15\36\1\0"+
    "\1\36\26\0\1\36\4\0\13\36\1\262\15\36\1\0"+
    "\1\36\26\0\1\36\4\0\22\36\1\263\6\36\1\0"+
    "\1\36\26\0\1\36\4\0\1\264\30\36\1\0\1\36"+
    "\26\0\1\36\4\0\22\36\1\265\6\36\1\0\1\36"+
    "\26\0\1\36\4\0\22\36\1\266\6\36\1\0\1\36"+
    "\55\0\1\267\36\0\1\36\4\0\13\36\1\270\15\36"+
    "\1\0\1\36\54\0\1\256\14\0\1\256\51\0\1\271"+
    "\47\0\1\272\74\0\1\273\45\0\1\274\4\0\6\274"+
    "\53\0\1\36\4\0\20\36\1\275\10\36\1\0\1\36"+
    "\53\0\1\276\40\0\1\36\4\0\16\36\1\277\12\36"+
    "\1\0\1\36\26\0\1\36\4\0\6\36\1\300\22\36"+
    "\1\0\1\36\41\0\1\301\52\0\1\36\4\0\12\36"+
    "\1\302\16\36\1\0\1\36\4\0\1\303\21\0\1\36"+
    "\4\0\4\36\1\304\24\36\1\0\1\36\26\0\1\36"+
    "\4\0\20\36\1\305\10\36\1\0\1\36\26\0\1\36"+
    "\4\0\4\36\1\306\24\36\1\0\1\36\26\0\1\36"+
    "\4\0\10\36\1\307\20\36\1\0\1\36\2\0\1\310"+
    "\40\0\1\310\24\0\1\310\23\0\1\36\4\0\20\36"+
    "\1\311\10\36\1\0\1\36\26\0\1\36\4\0\13\36"+
    "\1\312\15\36\1\0\1\36\53\0\1\313\60\0\1\314"+
    "\45\0\1\36\4\0\4\36\1\315\24\36\1\0\1\36"+
    "\26\0\1\36\4\0\13\36\1\316\15\36\1\0\1\36"+
    "\26\0\1\36\4\0\4\36\1\317\24\36\1\0\1\36"+
    "\26\0\1\36\4\0\1\320\30\36\1\0\1\36\12\0"+
    "\1\321\13\0\1\36\4\0\31\36\1\0\1\36\26\0"+
    "\1\36\4\0\15\36\1\322\13\36\1\0\1\36\26\0"+
    "\1\36\4\0\30\36\1\323\1\0\1\36\63\0\1\324"+
    "\30\0\1\36\4\0\10\36\1\325\20\36\1\0\1\36"+
    "\2\0\1\326\23\0\1\36\4\0\13\36\1\327\15\36"+
    "\1\0\1\36\26\0\1\36\4\0\31\36\1\0\1\330"+
    "\65\0\1\331\26\0\1\36\4\0\10\36\1\332\20\36"+
    "\1\0\1\36\2\0\1\333\23\0\1\36\4\0\2\36"+
    "\1\334\26\36\1\0\1\36\26\0\1\36\4\0\4\36"+
    "\1\335\24\36\1\0\1\36\26\0\1\36\4\0\4\36"+
    "\1\336\24\36\1\0\1\36\12\0\1\337\13\0\1\36"+
    "\4\0\31\36\1\0\1\36\26\0\1\36\4\0\13\36"+
    "\1\340\15\36\1\0\1\36\26\0\1\36\4\0\10\36"+
    "\1\341\20\36\1\0\1\36\2\0\1\342\23\0\1\36"+
    "\4\0\4\36\1\343\24\36\1\0\1\36\37\0\1\344"+
    "\54\0\1\36\4\0\16\36\1\345\12\36\1\0\1\36"+
    "\43\0\1\333\24\0\1\333\32\0\1\346\67\0\1\347"+
    "\54\0\1\350\4\0\6\350\53\0\1\36\4\0\22\36"+
    "\1\351\6\36\1\0\1\36\55\0\1\352\36\0\1\36"+
    "\4\0\20\36\1\353\10\36\1\0\1\36\26\0\1\36"+
    "\4\0\20\36\1\354\10\36\1\0\1\36\53\0\1\355"+
    "\40\0\1\36\4\0\20\36\1\356\10\36\1\0\1\36"+
    "\26\0\1\36\4\0\15\36\1\357\13\36\1\0\1\36"+
    "\26\0\1\36\4\0\24\36\1\360\4\36\1\0\1\36"+
    "\57\0\1\361\34\0\1\36\4\0\10\36\1\362\20\36"+
    "\1\0\1\36\2\0\1\363\23\0\1\36\4\0\4\36"+
    "\1\364\24\36\1\0\1\36\43\0\1\363\24\0\1\363"+
    "\34\0\1\365\54\0\1\36\4\0\3\36\1\366\25\36"+
    "\1\0\1\36\26\0\1\36\4\0\4\36\1\367\24\36"+
    "\1\0\1\36\26\0\1\36\4\0\15\36\1\370\13\36"+
    "\1\0\1\36\40\0\1\371\53\0\1\36\4\0\16\36"+
    "\1\372\12\36\1\0\1\36\51\0\1\373\42\0\1\36"+
    "\4\0\17\36\1\374\11\36\1\0\1\36\52\0\1\375"+
    "\41\0\1\36\4\0\4\36\1\376\24\36\1\0\1\36"+
    "\26\0\1\36\4\0\21\36\1\377\7\36\1\0\1\36"+
    "\3\0\1\u0100\50\0\1\u0100\14\0\1\u0100\22\0\1\36"+
    "\4\0\16\36\1\u0101\12\36\1\0\1\36\51\0\1\u0102"+
    "\42\0\1\36\4\0\2\36\1\u0103\17\36\1\u0104\6\36"+
    "\1\0\1\36\54\0\1\u0105\14\0\1\u0105\6\0\1\u0106"+
    "\13\0\1\36\4\0\31\36\1\0\1\36\26\0\1\36"+
    "\4\0\2\36\1\u0107\26\36\1\0\1\36\35\0\1\u0108"+
    "\56\0\1\36\4\0\25\36\1\u0109\3\36\1\0\1\36"+
    "\35\0\1\u010a\17\0\1\u010b\36\0\1\u010c\4\0\6\u010c"+
    "\53\0\1\36\4\0\1\u010d\30\36\1\0\1\36\33\0"+
    "\1\u010e\60\0\1\36\4\0\16\36\1\u010f\12\36\1\0"+
    "\1\36\51\0\1\u0110\42\0\1\36\4\0\22\36\1\u0111"+
    "\6\36\1\0\1\36\26\0\1\36\4\0\4\36\1\u0112"+
    "\24\36\1\0\1\36\37\0\1\u0113\54\0\1\36\4\0"+
    "\17\36\1\u0114\11\36\1\0\1\36\52\0\1\u0115\41\0"+
    "\1\36\4\0\6\36\1\u0116\22\36\1\0\1\36\41\0"+
    "\1\u0117\52\0\1\36\4\0\22\36\1\u0118\6\36\1\0"+
    "\1\36\33\0\1\u0119\60\0\1\36\4\0\15\36\1\u011a"+
    "\13\36\1\0\1\36\50\0\1\u011b\43\0\1\36\4\0"+
    "\13\36\1\u011c\15\36\1\0\1\36\46\0\1\u011d\45\0"+
    "\1\36\4\0\4\36\1\u011e\24\36\1\0\1\36\37\0"+
    "\1\u011f\54\0\1\36\4\0\15\36\1\u0120\13\36\1\0"+
    "\1\36\50\0\1\u0121\43\0\1\36\4\0\10\36\1\u0122"+
    "\20\36\1\0\1\36\2\0\1\u0123\40\0\1\u0124\24\0"+
    "\1\u0124\33\0\1\u0125\55\0\1\36\4\0\1\u0126\30\36"+
    "\1\0\1\36\33\0\1\u0127\75\0\1\u0123\24\0\1\u0123"+
    "\23\0\1\36\4\0\21\36\1\u0128\7\36\1\0\1\36"+
    "\3\0\1\u0129\50\0\1\u0129\14\0\1\u0129\22\0\1\36"+
    "\4\0\23\36\1\u012a\5\36\1\0\1\36\56\0\1\u012b"+
    "\35\0\1\36\4\0\22\36\1\u012c\6\36\1\0\1\36"+
    "\55\0\1\u012d\36\0\1\36\4\0\1\u012e\30\36\1\0"+
    "\1\36\33\0\1\u012f\101\0\1\u0130\44\0\1\36\4\0"+
    "\22\36\1\u0131\6\36\1\0\1\36\55\0\1\u0132\36\0"+
    "\1\36\4\0\4\36\1\u0133\24\36\1\0\1\36\37\0"+
    "\1\u0134\54\0\1\36\4\0\20\36\1\u0135\10\36\1\0"+
    "\1\36\53\0\1\u0136\40\0\1\36\4\0\16\36\1\u0137"+
    "\12\36\1\0\1\36\51\0\1\u0138\77\0\1\u0139\41\0"+
    "\1\u013a\54\0\1\36\4\0\13\36\1\u013b\15\36\1\0"+
    "\1\36\46\0\1\u013c\45\0\1\36\4\0\15\36\1\u013d"+
    "\13\36\1\0\1\36\50\0\1\u013e\43\0\1\36\4\0"+
    "\10\36\1\u013f\20\36\1\0\1\36\2\0\1\u0140\40\0"+
    "\1\u0140\24\0\1\u0140\23\0\1\36\4\0\1\36\1\u0141"+
    "\27\36\1\0\1\36\34\0\1\u0142\74\0\1\u0143\24\0"+
    "\1\u0143\23\0\1\36\4\0\1\u0144\30\36\1\0\1\36"+
    "\33\0\1\u0145\60\0\1\36\4\0\21\36\1\u0146\7\36"+
    "\1\0\1\36\3\0\1\u0147\50\0\1\u0147\14\0\1\u0147"+
    "\22\0\1\36\4\0\10\36\1\u0148\20\36\1\0\1\36"+
    "\2\0\1\u0149\40\0\1\u0149\24\0\1\u0149\23\0\1\36"+
    "\4\0\15\36\1\u014a\13\36\1\0\1\36\50\0\1\u014b"+
    "\54\0\1\u014c\40\0\1\u014d\101\0\1\36\4\0\3\36"+
    "\1\u014e\25\36\1\0\1\36\36\0\1\u014f\55\0\1\36"+
    "\4\0\16\36\1\u0150\12\36\1\0\1\36\51\0\1\u0151"+
    "\42\0\1\36\4\0\13\36\1\u0152\15\36\1\0\1\36"+
    "\46\0\1\u0153\65\0\1\u0154\45\0\1\36\4\0\13\36"+
    "\1\u0155\15\36\1\0\1\36\46\0\1\u0156\45\0\1\36"+
    "\4\0\5\36\1\u0157\23\36\1\0\1\36\40\0\1\u0158"+
    "\77\0\1\u0159\1\0\1\u015a\14\0\1\u015a\6\0\1\u015b"+
    "\13\0\1\36\4\0\31\36\1\0\1\36\12\0\1\u015b"+
    "\101\0\1\36\4\0\15\36\1\u015c\13\36\1\0\1\36"+
    "\50\0\1\u015d\43\0\1\36\4\0\4\36\1\u015e\24\36"+
    "\1\0\1\36\37\0\1\u015f\110\0\1\u0160\56\0\1\u0161"+
    "\51\0\1\u0162\63\0\1\u0163\56\0\1\36\4\0\21\36"+
    "\1\u0164\7\36\1\0\1\36\3\0\1\u0165\50\0\1\u0165"+
    "\14\0\1\u0165\33\0\1\u0166\63\0\1\u0167\101\0\1\u0168"+
    "\55\0\1\u0169\61\0\1\u016a\76\0\1\u016b\75\0\1\u016c"+
    "\52\0\1\u016d\24\0\1\u016d\46\0\1\u016e\64\0\1\u016f"+
    "\66\0\1\u0170\67\0\1\u0171\67\0\1\u0172\60\0\1\u0173"+
    "\50\0\1\u0174\71\0\1\u0175\102\0\1\u0176\14\0\1\u0176"+
    "\50\0\1\u0177\14\0\1\u0177\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[16038];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\1\1\6\11\1\1\1\11"+
    "\1\1\4\11\23\1\1\11\1\1\2\11\1\1\1\11"+
    "\2\1\1\11\2\0\1\1\1\0\20\1\1\0\11\1"+
    "\1\0\6\1\3\0\2\11\2\0\2\1\1\0\11\1"+
    "\1\0\11\1\1\0\12\1\1\11\5\1\1\0\1\1"+
    "\4\0\3\1\1\0\2\1\1\0\6\1\1\0\2\1"+
    "\2\0\11\1\1\0\1\1\1\11\5\1\1\0\10\1"+
    "\1\0\1\1\4\0\1\1\1\0\2\1\1\0\1\1"+
    "\1\11\4\1\1\0\2\1\2\0\4\1\1\0\2\1"+
    "\1\0\1\1\1\0\2\1\1\0\1\1\1\0\3\1"+
    "\1\0\2\1\1\0\1\1\1\11\1\1\1\0\1\11"+
    "\1\0\1\1\1\0\2\1\1\0\3\1\1\0\1\1"+
    "\1\0\1\1\1\0\3\1\1\0\1\1\1\0\1\1"+
    "\1\0\2\1\1\0\1\1\1\0\2\1\2\0\1\1"+
    "\1\0\1\1\1\0\2\11\1\1\1\0\1\1\1\0"+
    "\2\1\1\11\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\11"+
    "\1\1\3\0\1\1\1\0\1\1\1\11\1\1\1\0"+
    "\1\1\1\0\1\1\2\0\1\1\1\0\3\1\1\0"+
    "\1\1\3\0\1\1\1\11\1\1\1\0\1\1\1\0"+
    "\1\1\2\0\1\1\1\0\1\1\1\11\1\1\1\0"+
    "\1\1\2\11\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\2\0\1\1\1\11\1\1\1\11\3\0\1\1\1\11"+
    "\1\1\1\0\1\11\3\0\1\1\1\11\13\0\1\11"+
    "\4\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[375];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // Utils
    private StringBuilder string;

    // Error Handling
    private ArrayList<String> symbols;
    private ArrayList<ErrorReport> lexicalErrors;

    private void error(String token) {
        this.lexicalErrors.add(new ErrorReport(token, yyline, yycolumn, "Lexico", "Cadena no existente en el lenguaje"));
    }

    public ArrayList<ErrorReport> getLexicalErrors(){
        return this.lexicalErrors;
    }

    public ArrayList<String> getSymbols(){
        return this.symbols;
    }

    //Parser Code
    private Symbol symbol(int type) {
        this.symbols.add(yytext());
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        this.symbols.add(value.toString());
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerPKM(java.io.Reader in) {
      this.string = new StringBuilder();
    this.symbols = new ArrayList<>();
    this.lexicalErrors = new ArrayList<>();
    yyline = 1;
    yycolumn = 1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(symPKM.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error(yytext());
            }
          // fall through
          case 70: break;
          case 2:
            { /* Ignore */
            }
          // fall through
          case 71: break;
          case 3:
            { this.string.setLength(0); yybegin(TEXT);
            }
          // fall through
          case 72: break;
          case 4:
            { return symbol(symPKM.MODULO);
            }
          // fall through
          case 73: break;
          case 5:
            { return symbol(symPKM.PARENTESIS_ABIERTO);
            }
          // fall through
          case 74: break;
          case 6:
            { return symbol(symPKM.PARENTESIS_CERRADO);
            }
          // fall through
          case 75: break;
          case 7:
            { return symbol(symPKM.MULTIPLICACION);
            }
          // fall through
          case 76: break;
          case 8:
            { return symbol(symPKM.SUMA);
            }
          // fall through
          case 77: break;
          case 9:
            { return symbol(symPKM.COMA);
            }
          // fall through
          case 78: break;
          case 10:
            { return symbol(symPKM.RESTA);
            }
          // fall through
          case 79: break;
          case 11:
            { return symbol(symPKM.DIAGONAL);
            }
          // fall through
          case 80: break;
          case 12:
            { return symbol(symPKM.NUMERO_ENTERO, Integer.parseInt(yytext()));
            }
          // fall through
          case 81: break;
          case 13:
            { return symbol(symPKM.DOS_PUNTOS);
            }
          // fall through
          case 82: break;
          case 14:
            { return symbol(symPKM.MENOR);
            }
          // fall through
          case 83: break;
          case 15:
            { return symbol(symPKM.IGUAL);
            }
          // fall through
          case 84: break;
          case 16:
            { return symbol(symPKM.MAYOR);
            }
          // fall through
          case 85: break;
          case 17:
            { return symbol(symPKM.ID, yytext());
            }
          // fall through
          case 86: break;
          case 18:
            { return symbol(symPKM.POTENCIA);
            }
          // fall through
          case 87: break;
          case 19:
            { return symbol(symPKM.LLAVE_ABIERTO);
            }
          // fall through
          case 88: break;
          case 20:
            { return symbol(symPKM.LLAVE_CERRADO);
            }
          // fall through
          case 89: break;
          case 21:
            { this.string.append(yytext());
            }
          // fall through
          case 90: break;
          case 22:
            { this.string.append("\n");
            }
          // fall through
          case 91: break;
          case 23:
            { System.out.println("TEXTO:" + this.string.toString().trim());
        yybegin(YYINITIAL);
        return symbol(symPKM.TEXTO, this.string.toString().trim());
            }
          // fall through
          case 92: break;
          case 24:
            { return symbol(symPKM.NUMERO_ENTERO_NEGATIVO, Integer.parseInt(yytext()));
            }
          // fall through
          case 93: break;
          case 25:
            { return symbol(symPKM.SEPARADOR);
            }
          // fall through
          case 94: break;
          case 26:
            { return symbol(symPKM.NUMERO_DECIMAL, Double.parseDouble(yytext()));
            }
          // fall through
          case 95: break;
          case 27:
            { return symbol(symPKM.RED);
            }
          // fall through
          case 96: break;
          case 28:
            { return symbol(symPKM.SKY);
            }
          // fall through
          case 97: break;
          case 29:
            { this.string.setLength(0);
        this.string.append(yytext());
        this.string.deleteCharAt(0);
        return symbol(symPKM.HEXADECIMAL, this.string.toString().trim());
            }
          // fall through
          case 98: break;
          case 30:
            { return symbol(symPKM.NUMERO_DECIMAL_NEGATIVO, Double.parseDouble(yytext()));
            }
          // fall through
          case 99: break;
          case 31:
            { return symbol(symPKM.BLUE);
            }
          // fall through
          case 100: break;
          case 32:
            { return symbol(symPKM.DROP_ETIQUETA);
            }
          // fall through
          case 101: break;
          case 33:
            { return symbol(symPKM.HORA);
            }
          // fall through
          case 102: break;
          case 34:
            { return symbol(symPKM.LINE_ETIQUETA);
            }
          // fall through
          case 103: break;
          case 35:
            { return symbol(symPKM.MONO);
            }
          // fall through
          case 104: break;
          case 36:
            { return symbol(symPKM.OPEN_ETIQUETA);
            }
          // fall through
          case 105: break;
          case 37:
            { return symbol(symPKM.TEXT_ETIQUETA);
            }
          // fall through
          case 106: break;
          case 38:
            { return symbol(symPKM.BLACK);
            }
          // fall through
          case 107: break;
          case 39:
            { return symbol(symPKM.COLOR_ETIQUETA);
            }
          // fall through
          case 108: break;
          case 40:
            { return symbol(symPKM.FECHA);
            }
          // fall through
          case 109: break;
          case 41:
            { return symbol(symPKM.GREEN);
            }
          // fall through
          case 110: break;
          case 42:
            { return symbol(symPKM.STYLE_ETIQUETA);
            }
          // fall through
          case 111: break;
          case 43:
            { return symbol(symPKM.TABLE_ETIQUETA);
            }
          // fall through
          case 112: break;
          case 44:
            { return symbol(symPKM.WHITE);
            }
          // fall through
          case 113: break;
          case 45:
            { return symbol(symPKM.AUTHOR);
            }
          // fall through
          case 114: break;
          case 46:
            { return symbol(symPKM.BORDER_ETIQUETA);
            }
          // fall through
          case 115: break;
          case 47:
            { return symbol(symPKM.DOTTED);
            }
          // fall through
          case 116: break;
          case 48:
            { return symbol(symPKM.DOUBLE);
            }
          // fall through
          case 117: break;
          case 49:
            { return symbol(symPKM.PURPLE);
            }
          // fall through
          case 118: break;
          case 50:
            { return symbol(symPKM.SELECT_ETIQUETA);
            }
          // fall through
          case 119: break;
          case 51:
            { return symbol(symPKM.YELLOW);
            }
          // fall through
          case 120: break;
          case 52:
            { return symbol(symPKM.CONTENT_ETIQUETA);
            }
          // fall through
          case 121: break;
          case 53:
            { return symbol(symPKM.CURSIVE);
            }
          // fall through
          case 122: break;
          case 54:
            { return symbol(symPKM.ELEMENT_ETIQUETA);
            }
          // fall through
          case 123: break;
          case 55:
            { return symbol(symPKM.SECTION_ETIQUETA);
            }
          // fall through
          case 124: break;
          case 56:
            { return symbol(symPKM.ABIERTAS);
            }
          // fall through
          case 125: break;
          case 57:
            { return symbol(symPKM.MULTIPLE_ETIQUETA);
            }
          // fall through
          case 126: break;
          case 58:
            { return symbol(symPKM.VERTICAL);
            }
          // fall through
          case 127: break;
          case 59:
            { return symbol(symPKM.MULTIPLES);
            }
          // fall through
          case 128: break;
          case 60:
            { return symbol(symPKM.SELECCION);
            }
          // fall through
          case 129: break;
          case 61:
            { return symbol(symPKM.TEXT_SIZE_ETIQUETA);
            }
          // fall through
          case 130: break;
          case 62:
            { return symbol(symPKM.HORIZONTAL);
            }
          // fall through
          case 131: break;
          case 63:
            { return symbol(symPKM.SANS_SERIF);
            }
          // fall through
          case 132: break;
          case 64:
            { return symbol(symPKM.DESCRIPTION);
            }
          // fall through
          case 133: break;
          case 65:
            { return symbol(symPKM.FONT_FAMILY_ETIQUETA);
            }
          // fall through
          case 134: break;
          case 66:
            { return symbol(symPKM.DESPLEGABLES);
            }
          // fall through
          case 135: break;
          case 67:
            { return symbol(symPKM.BACKGROUND_COLOR_ETIQUETA);
            }
          // fall through
          case 136: break;
          case 68:
            { return symbol(symPKM.TOTAL_PREGUNTAS);
            }
          // fall through
          case 137: break;
          case 69:
            { return symbol(symPKM.TOTAL_SECCIONES);
            }
          // fall through
          case 138: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
