
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyecto1_compi1_ps26.domain.analyzers.saved_pkm;

import java_cup.runtime.*;
import java.util.*;
import com.example.proyecto1_compi1_ps26.domain.entities.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserPKM extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return symPKM.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserPKM() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserPKM(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserPKM(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\131\000\002\002\004\000\002\002\006\000\002\003" +
    "\040\000\002\004\004\000\002\004\003\000\002\006\003" +
    "\000\002\006\003\000\002\006\003\000\002\006\003\000" +
    "\002\013\012\000\002\014\046\000\002\015\003\000\002" +
    "\015\003\000\002\015\003\000\002\015\003\000\002\020" +
    "\011\000\002\021\011\000\002\022\003\000\002\022\003" +
    "\000\002\022\003\000\002\022\003\000\002\022\003\000" +
    "\002\022\003\000\002\022\003\000\002\022\003\000\002" +
    "\016\003\000\002\016\003\000\002\016\003\000\002\017" +
    "\003\000\002\017\003\000\002\017\003\000\002\007\034" +
    "\000\002\023\003\000\002\023\003\000\002\026\004\000" +
    "\002\026\003\000\002\030\003\000\002\030\003\000\002" +
    "\030\003\000\002\030\003\000\002\027\004\000\002\027" +
    "\003\000\002\031\012\000\002\032\013\000\002\032\012" +
    "\000\002\010\022\000\002\011\013\000\002\033\004\000" +
    "\002\033\010\000\002\012\003\000\002\012\003\000\002" +
    "\012\003\000\002\034\021\000\002\040\005\000\002\040" +
    "\003\000\002\041\003\000\002\041\003\000\002\042\004" +
    "\000\002\042\010\000\002\035\021\000\002\043\004\000" +
    "\002\043\010\000\002\036\024\000\002\045\003\000\002" +
    "\045\002\000\002\046\005\000\002\046\003\000\002\044" +
    "\004\000\002\044\010\000\002\005\005\000\002\005\003" +
    "\000\002\050\005\000\002\050\003\000\002\052\005\000" +
    "\002\052\003\000\002\054\005\000\002\054\003\000\002" +
    "\054\003\000\002\054\003\000\002\047\003\000\002\047" +
    "\003\000\002\051\003\000\002\051\003\000\002\053\003" +
    "\000\002\053\003\000\002\037\005\000\002\037\003\000" +
    "\002\055\003\000\002\055\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u013c\000\004\004\004\001\002\000\004\006\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\005\u0122\001\002\000\004\004\011\001\002\000" +
    "\004\061\015\001\002\000\006\002\ufffd\061\ufffd\001\002" +
    "\000\006\002\uffd0\061\uffd0\001\002\000\006\002\ufffb\061" +
    "\ufffb\001\002\000\016\030\031\032\026\035\032\036\025" +
    "\037\027\040\030\001\002\000\006\002\ufffc\061\ufffc\001" +
    "\002\000\006\002\ufffa\061\ufffa\001\002\000\006\002\uffcf" +
    "\061\uffcf\001\002\000\006\002\ufff9\061\ufff9\001\002\000" +
    "\006\002\uffce\061\uffce\001\002\000\006\002\000\061\015" +
    "\001\002\000\006\002\ufffe\061\ufffe\001\002\000\004\063" +
    "\u010d\001\002\000\004\062\346\001\002\000\004\063\317" +
    "\001\002\000\004\063\253\001\002\000\004\063\213\001" +
    "\002\000\004\063\033\001\002\000\012\066\043\073\034" +
    "\103\035\105\042\001\002\000\044\004\uffb3\013\uffb3\014" +
    "\uffb3\015\uffb3\016\uffb3\017\uffb3\062\uffb3\064\uffb3\065\uffb3" +
    "\067\uffb3\071\uffb3\075\uffb3\076\uffb3\077\uffb3\100\uffb3\101" +
    "\uffb3\102\uffb3\001\002\000\044\004\uffb5\013\uffb5\014\uffb5" +
    "\015\uffb5\016\uffb5\017\uffb5\062\uffb5\064\uffb5\065\uffb5\067" +
    "\uffb5\071\uffb5\075\uffb5\076\uffb5\077\uffb5\100\uffb5\101\uffb5" +
    "\102\uffb5\001\002\000\010\064\062\075\047\076\045\001" +
    "\002\000\040\004\uffbb\013\uffbb\014\uffbb\015\uffbb\016\uffbb" +
    "\017\uffbb\062\uffbb\064\uffbb\065\uffbb\067\uffbb\071\uffbb\075" +
    "\uffbb\076\uffbb\077\052\100\054\001\002\000\044\004\uffb9" +
    "\013\uffb9\014\uffb9\015\uffb9\016\uffb9\017\uffb9\062\uffb9\064" +
    "\uffb9\065\uffb9\067\uffb9\071\uffb9\075\uffb9\076\uffb9\077\uffb9" +
    "\100\uffb9\101\056\102\057\001\002\000\044\004\uffb7\013" +
    "\uffb7\014\uffb7\015\uffb7\016\uffb7\017\uffb7\062\uffb7\064\uffb7" +
    "\065\uffb7\067\uffb7\071\uffb7\075\uffb7\076\uffb7\077\uffb7\100" +
    "\uffb7\101\uffb7\102\uffb7\001\002\000\044\004\uffb4\013\uffb4" +
    "\014\uffb4\015\uffb4\016\uffb4\017\uffb4\062\uffb4\064\uffb4\065" +
    "\uffb4\067\uffb4\071\uffb4\075\uffb4\076\uffb4\077\uffb4\100\uffb4" +
    "\101\uffb4\102\uffb4\001\002\000\012\066\043\073\034\103" +
    "\035\105\042\001\002\000\010\067\050\075\047\076\045" +
    "\001\002\000\012\066\uffb1\073\uffb1\103\uffb1\105\uffb1\001" +
    "\002\000\012\066\043\073\034\103\035\105\042\001\002" +
    "\000\012\066\uffb2\073\uffb2\103\uffb2\105\uffb2\001\002\000" +
    "\044\004\uffb6\013\uffb6\014\uffb6\015\uffb6\016\uffb6\017\uffb6" +
    "\062\uffb6\064\uffb6\065\uffb6\067\uffb6\071\uffb6\075\uffb6\076" +
    "\uffb6\077\uffb6\100\uffb6\101\uffb6\102\uffb6\001\002\000\040" +
    "\004\uffbc\013\uffbc\014\uffbc\015\uffbc\016\uffbc\017\uffbc\062" +
    "\uffbc\064\uffbc\065\uffbc\067\uffbc\071\uffbc\075\uffbc\076\uffbc" +
    "\077\052\100\054\001\002\000\012\066\uffb0\073\uffb0\103" +
    "\uffb0\105\uffb0\001\002\000\012\066\043\073\034\103\035" +
    "\105\042\001\002\000\012\066\uffaf\073\uffaf\103\uffaf\105" +
    "\uffaf\001\002\000\044\004\uffba\013\uffba\014\uffba\015\uffba" +
    "\016\uffba\017\uffba\062\uffba\064\uffba\065\uffba\067\uffba\071" +
    "\uffba\075\uffba\076\uffba\077\uffba\100\uffba\101\056\102\057" +
    "\001\002\000\012\066\uffae\073\uffae\103\uffae\105\uffae\001" +
    "\002\000\012\066\uffad\073\uffad\103\uffad\105\uffad\001\002" +
    "\000\012\066\043\073\034\103\035\105\042\001\002\000" +
    "\044\004\uffb8\013\uffb8\014\uffb8\015\uffb8\016\uffb8\017\uffb8" +
    "\062\uffb8\064\uffb8\065\uffb8\067\uffb8\071\uffb8\075\uffb8\076" +
    "\uffb8\077\uffb8\100\uffb8\101\uffb8\102\uffb8\001\002\000\012" +
    "\066\043\073\034\103\035\105\042\001\002\000\010\064" +
    "\064\075\047\076\045\001\002\000\004\074\065\001\002" +
    "\000\006\062\070\065\066\001\002\000\004\062\212\001" +
    "\002\000\006\002\uffd3\061\uffd3\001\002\000\004\061\072" +
    "\001\002\000\004\061\206\001\002\000\004\022\073\001" +
    "\002\000\004\062\074\001\002\000\004\061\076\001\002" +
    "\000\004\061\202\001\002\000\004\023\077\001\002\000" +
    "\004\063\100\001\002\000\030\041\114\042\110\043\101" +
    "\044\113\045\102\046\112\047\117\050\104\061\103\066" +
    "\111\072\116\001\002\000\004\065\uffee\001\002\000\004" +
    "\065\uffec\001\002\000\012\066\043\073\034\103\035\105" +
    "\042\001\002\000\004\065\uffe9\001\002\000\004\065\ufff3" +
    "\001\002\000\004\065\126\001\002\000\004\065\ufff5\001" +
    "\002\000\004\065\uffef\001\002\000\012\066\043\073\034" +
    "\103\035\105\042\001\002\000\004\065\uffeb\001\002\000" +
    "\004\065\uffed\001\002\000\004\065\ufff0\001\002\000\004" +
    "\065\ufff4\001\002\000\004\065\ufff6\001\002\000\004\065" +
    "\uffea\001\002\000\010\064\121\075\047\076\045\001\002" +
    "\000\012\066\043\073\034\103\035\105\042\001\002\000" +
    "\010\064\123\075\047\076\045\001\002\000\012\066\043" +
    "\073\034\103\035\105\042\001\002\000\010\067\125\075" +
    "\047\076\045\001\002\000\004\065\ufff2\001\002\000\004" +
    "\062\127\001\002\000\004\061\130\001\002\000\004\024" +
    "\131\001\002\000\004\063\132\001\002\000\030\041\114" +
    "\042\110\043\101\044\113\045\102\046\112\047\117\050" +
    "\104\061\103\066\111\072\116\001\002\000\004\065\134" +
    "\001\002\000\004\062\135\001\002\000\004\061\136\001" +
    "\002\000\004\025\137\001\002\000\004\063\140\001\002" +
    "\000\010\053\141\054\144\055\142\001\002\000\004\065" +
    "\uffe8\001\002\000\004\065\uffe6\001\002\000\004\065\145" +
    "\001\002\000\004\065\uffe7\001\002\000\004\062\146\001" +
    "\002\000\004\061\147\001\002\000\004\026\150\001\002" +
    "\000\004\063\151\001\002\000\012\066\043\073\034\103" +
    "\035\105\042\001\002\000\010\065\153\075\047\076\045" +
    "\001\002\000\004\062\154\001\002\000\004\061\155\001" +
    "\002\000\004\027\156\001\002\000\004\064\157\001\002" +
    "\000\012\066\043\073\034\103\035\105\042\001\002\000" +
    "\010\064\161\075\047\076\045\001\002\000\010\056\164" +
    "\057\165\060\163\001\002\000\004\064\166\001\002\000" +
    "\004\064\uffe3\001\002\000\004\064\uffe5\001\002\000\004" +
    "\064\uffe4\001\002\000\004\023\167\001\002\000\004\063" +
    "\170\001\002\000\030\041\114\042\110\043\101\044\113" +
    "\045\102\046\112\047\117\050\104\061\103\066\111\072" +
    "\116\001\002\000\004\065\172\001\002\000\004\062\173" +
    "\001\002\000\004\061\ufff7\001\002\000\010\064\175\075" +
    "\047\076\045\001\002\000\012\066\043\073\034\103\035" +
    "\105\042\001\002\000\010\064\177\075\047\076\045\001" +
    "\002\000\012\066\043\073\034\103\035\105\042\001\002" +
    "\000\010\062\201\075\047\076\045\001\002\000\004\065" +
    "\ufff1\001\002\000\004\065\203\001\002\000\004\022\204" +
    "\001\002\000\004\062\205\001\002\000\004\061\ufff8\001" +
    "\002\000\004\065\207\001\002\000\004\035\210\001\002" +
    "\000\004\062\211\001\002\000\006\002\uffd1\061\uffd1\001" +
    "\002\000\006\002\uffd2\061\uffd2\001\002\000\012\066\043" +
    "\073\034\103\035\105\042\001\002\000\010\064\215\075" +
    "\047\076\045\001\002\000\012\066\043\073\034\103\035" +
    "\105\042\001\002\000\010\064\217\075\047\076\045\001" +
    "\002\000\012\066\043\073\034\103\035\105\042\001\002" +
    "\000\010\064\221\075\047\076\045\001\002\000\012\066" +
    "\043\073\034\103\035\105\042\001\002\000\010\064\223" +
    "\075\047\076\045\001\002\000\006\051\226\052\224\001" +
    "\002\000\004\062\uffe0\001\002\000\004\062\227\001\002" +
    "\000\004\062\uffe1\001\002\000\004\061\072\001\002\000" +
    "\004\061\231\001\002\000\004\031\232\001\002\000\004" +
    "\062\233\001\002\000\004\061\015\001\002\000\004\061" +
    "\uffdb\001\002\000\004\061\242\001\002\000\004\061\uffde" +
    "\001\002\000\004\061\uffdd\001\002\000\004\061\uffda\001" +
    "\002\000\004\061\uffdc\001\002\000\020\030\031\032\026" +
    "\035\032\036\025\037\027\040\030\065\244\001\002\000" +
    "\004\061\uffdf\001\002\000\004\031\245\001\002\000\004" +
    "\062\246\001\002\000\004\061\247\001\002\000\004\065" +
    "\250\001\002\000\004\030\251\001\002\000\004\062\252" +
    "\001\002\000\006\002\uffe2\061\uffe2\001\002\000\012\066" +
    "\043\073\034\103\035\105\042\001\002\000\010\064\255" +
    "\075\047\076\045\001\002\000\012\066\043\073\034\103" +
    "\035\105\042\001\002\000\010\064\257\075\047\076\045" +
    "\001\002\000\014\066\043\073\034\074\260\103\035\105" +
    "\042\001\002\000\010\064\uffaa\071\uffaa\075\uffaa\001\002" +
    "\000\010\064\uffab\071\uffab\075\uffab\001\002\000\012\064" +
    "\uffa9\071\uffa9\075\047\076\045\001\002\000\006\064\264" +
    "\075\265\001\002\000\004\070\267\001\002\000\014\066" +
    "\043\073\034\074\260\103\035\105\042\001\002\000\010" +
    "\064\uffac\071\uffac\075\uffac\001\002\000\014\066\043\073" +
    "\034\074\260\103\035\105\042\001\002\000\006\064\272" +
    "\071\273\001\002\000\010\064\uffcb\071\uffcb\075\265\001" +
    "\002\000\014\066\043\073\034\074\260\103\035\105\042" +
    "\001\002\000\004\064\274\001\002\000\004\070\275\001" +
    "\002\000\014\066\043\071\uffc1\073\034\103\035\105\042" +
    "\001\002\000\012\064\uffbf\071\uffbf\075\047\076\045\001" +
    "\002\000\006\064\314\071\uffc2\001\002\000\004\071\301" +
    "\001\002\000\004\064\302\001\002\000\006\062\305\065" +
    "\304\001\002\000\006\002\uffc3\061\uffc3\001\002\000\004" +
    "\062\313\001\002\000\004\061\072\001\002\000\004\061" +
    "\307\001\002\000\004\065\310\001\002\000\004\040\311" +
    "\001\002\000\004\062\312\001\002\000\006\002\uffbd\061" +
    "\uffbd\001\002\000\006\002\uffbe\061\uffbe\001\002\000\012" +
    "\066\043\073\034\103\035\105\042\001\002\000\012\064" +
    "\uffc0\071\uffc0\075\047\076\045\001\002\000\010\064\uffcc" +
    "\071\uffcc\075\265\001\002\000\012\066\043\073\034\103" +
    "\035\105\042\001\002\000\010\064\321\075\047\076\045" +
    "\001\002\000\012\066\043\073\034\103\035\105\042\001" +
    "\002\000\010\064\323\075\047\076\045\001\002\000\014" +
    "\066\043\073\034\074\260\103\035\105\042\001\002\000" +
    "\006\064\325\075\265\001\002\000\004\070\326\001\002" +
    "\000\014\066\043\073\034\074\260\103\035\105\042\001" +
    "\002\000\006\064\272\071\330\001\002\000\004\064\331" +
    "\001\002\000\006\105\334\106\332\001\002\000\006\062" +
    "\uffc9\065\uffc9\001\002\000\006\062\337\065\336\001\002" +
    "\000\006\062\uffca\065\uffca\001\002\000\006\002\uffc6\061" +
    "\uffc6\001\002\000\004\062\345\001\002\000\004\061\072" +
    "\001\002\000\004\061\341\001\002\000\004\065\342\001" +
    "\002\000\004\037\343\001\002\000\004\062\344\001\002" +
    "\000\006\002\uffc4\061\uffc4\001\002\000\006\002\uffc5\061" +
    "\uffc5\001\002\000\004\061\072\001\002\000\004\061\350" +
    "\001\002\000\004\031\351\001\002\000\004\062\352\001" +
    "\002\000\004\061\355\001\002\000\004\061\u0105\001\002" +
    "\000\004\061\uffd8\001\002\000\004\033\356\001\002\000" +
    "\004\062\357\001\002\000\004\061\360\001\002\000\004" +
    "\034\375\001\002\000\004\061\362\001\002\000\006\034" +
    "\364\065\363\001\002\000\004\033\373\001\002\000\004" +
    "\062\365\001\002\000\004\061\015\001\002\000\004\061" +
    "\367\001\002\000\004\065\370\001\002\000\004\034\371" +
    "\001\002\000\004\062\372\001\002\000\004\061\uffd6\001" +
    "\002\000\004\062\374\001\002\000\004\061\uffd7\001\002" +
    "\000\004\062\376\001\002\000\004\061\015\001\002\000" +
    "\004\061\u0100\001\002\000\004\065\u0101\001\002\000\004" +
    "\034\u0102\001\002\000\004\062\u0103\001\002\000\004\061" +
    "\uffd5\001\002\000\004\061\uffd9\001\002\000\006\033\356" +
    "\065\u0106\001\002\000\004\031\u0107\001\002\000\004\062" +
    "\u0108\001\002\000\004\061\u0109\001\002\000\004\065\u010a" +
    "\001\002\000\004\032\u010b\001\002\000\004\062\u010c\001" +
    "\002\000\006\002\uffd4\061\uffd4\001\002\000\012\066\043" +
    "\073\034\103\035\105\042\001\002\000\010\064\u010f\075" +
    "\047\076\045\001\002\000\012\066\043\073\034\103\035" +
    "\105\042\001\002\000\010\064\u0111\075\047\076\045\001" +
    "\002\000\014\066\043\073\034\074\260\103\035\105\042" +
    "\001\002\000\006\064\u0113\075\265\001\002\000\004\070" +
    "\u0114\001\002\000\014\066\043\073\034\074\260\103\035" +
    "\105\042\001\002\000\006\064\272\071\u0116\001\002\000" +
    "\004\064\u0117\001\002\000\006\105\334\106\332\001\002" +
    "\000\006\062\u011b\065\u011a\001\002\000\006\002\uffcd\061" +
    "\uffcd\001\002\000\004\062\u0121\001\002\000\004\061\072" +
    "\001\002\000\004\061\u011d\001\002\000\004\065\u011e\001" +
    "\002\000\004\036\u011f\001\002\000\004\062\u0120\001\002" +
    "\000\006\002\uffc7\061\uffc7\001\002\000\006\002\uffc8\061" +
    "\uffc8\001\002\000\004\073\u0123\001\002\000\004\007\u0124" +
    "\001\002\000\004\005\u0125\001\002\000\004\020\u0126\001" +
    "\002\000\004\010\u0127\001\002\000\004\005\u0128\001\002" +
    "\000\004\021\u0129\001\002\000\004\011\u012a\001\002\000" +
    "\004\005\u012b\001\002\000\004\074\u012c\001\002\000\004" +
    "\012\u012d\001\002\000\004\005\u012e\001\002\000\012\066" +
    "\043\073\034\103\035\105\042\001\002\000\010\013\u0130" +
    "\075\047\076\045\001\002\000\004\005\u0131\001\002\000" +
    "\012\066\043\073\034\103\035\105\042\001\002\000\010" +
    "\014\u0133\075\047\076\045\001\002\000\004\005\u0134\001" +
    "\002\000\012\066\043\073\034\103\035\105\042\001\002" +
    "\000\010\015\u0136\075\047\076\045\001\002\000\004\005" +
    "\u0137\001\002\000\012\066\043\073\034\103\035\105\042" +
    "\001\002\000\010\016\u0139\075\047\076\045\001\002\000" +
    "\004\005\u013a\001\002\000\012\066\043\073\034\103\035" +
    "\105\042\001\002\000\010\017\u013c\075\047\076\045\001" +
    "\002\000\004\005\u013d\001\002\000\012\066\043\073\034" +
    "\103\035\105\042\001\002\000\010\004\uffff\075\047\076" +
    "\045\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u013c\000\004\002\004\001\001\000\004\003\007\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\024\004\022\006\011\007\015\010" +
    "\013\011\016\012\020\034\012\035\017\036\021\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\006" +
    "\023\007\015\010\013\011\016\012\020\034\012\035\017" +
    "\036\021\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\005\035\050\036\052" +
    "\037\054\040\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\047\045\001\001\000\004\051\052\001\001\000" +
    "\004\053\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\005\043\050\036\052\037\054\040\001\001\000" +
    "\004\047\045\001\001\000\002\001\001\000\010\050\050" +
    "\052\037\054\040\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\051\052\001\001\000\002\001\001\000\006" +
    "\052\054\054\040\001\001\000\002\001\001\000\004\053" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\054\060\001\001\000\002\001\001\000\012\005\062\050" +
    "\036\052\037\054\040\001\001\000\004\047\045\001\001" +
    "\000\002\001\001\000\004\033\066\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\013\070\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\074\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\015\105\020\106\021\114\022\104\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\005\173" +
    "\050\036\052\037\054\040\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\005\117\050\036\052\037\054\040\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\047\045\001\001\000\012\005\121\050\036\052\037" +
    "\054\040\001\001\000\004\047\045\001\001\000\012\005" +
    "\123\050\036\052\037\054\040\001\001\000\004\047\045" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\015\132" +
    "\020\106\021\114\022\104\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\016\142\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\005\151\050\036\052\037\054\040\001\001" +
    "\000\004\047\045\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\005\157" +
    "\050\036\052\037\054\040\001\001\000\004\047\045\001" +
    "\001\000\004\017\161\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\015\170\020\106\021\114" +
    "\022\104\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\047\045\001\001\000\012\005\175" +
    "\050\036\052\037\054\040\001\001\000\004\047\045\001" +
    "\001\000\012\005\177\050\036\052\037\054\040\001\001" +
    "\000\004\047\045\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\005\213\050\036" +
    "\052\037\054\040\001\001\000\004\047\045\001\001\000" +
    "\012\005\215\050\036\052\037\054\040\001\001\000\004" +
    "\047\045\001\001\000\012\005\217\050\036\052\037\054" +
    "\040\001\001\000\004\047\045\001\001\000\012\005\221" +
    "\050\036\052\037\054\040\001\001\000\004\047\045\001" +
    "\001\000\004\023\224\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\227\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\024" +
    "\007\236\010\233\011\237\012\240\026\234\030\235\034" +
    "\012\035\017\036\021\001\001\000\002\001\001\000\022" +
    "\007\236\010\233\011\237\012\240\030\242\034\012\035" +
    "\017\036\021\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\005\253\050\036\052\037" +
    "\054\040\001\001\000\004\047\045\001\001\000\012\005" +
    "\255\050\036\052\037\054\040\001\001\000\004\047\045" +
    "\001\001\000\016\005\261\037\262\050\036\052\037\054" +
    "\040\055\260\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\047\045\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\005\261\050\036\052\037\054\040\055\265" +
    "\001\001\000\002\001\001\000\020\005\261\037\270\040" +
    "\267\050\036\052\037\054\040\055\260\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\005\261\037\315\050" +
    "\036\052\037\054\040\055\260\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\005\275\045\277\046\276\050" +
    "\036\052\037\054\040\001\001\000\004\047\045\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\044\302\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\013\305\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\005\314\050\036\052\037\054" +
    "\040\001\001\000\004\047\045\001\001\000\002\001\001" +
    "\000\012\005\317\050\036\052\037\054\040\001\001\000" +
    "\004\047\045\001\001\000\012\005\321\050\036\052\037" +
    "\054\040\001\001\000\004\047\045\001\001\000\016\005" +
    "\261\037\323\050\036\052\037\054\040\055\260\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\005\261\037" +
    "\270\040\326\050\036\052\037\054\040\055\260\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\041\332\001" +
    "\001\000\002\001\001\000\004\043\334\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\013" +
    "\337\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\013\346\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\027\352\031\353\001" +
    "\001\000\004\031\u0103\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\032\360\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\022\007\236\010\233\011" +
    "\237\012\240\030\365\034\012\035\017\036\021\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\022\007\236\010\233\011" +
    "\237\012\240\030\376\034\012\035\017\036\021\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\005\u010d\050\036\052\037\054" +
    "\040\001\001\000\004\047\045\001\001\000\012\005\u010f" +
    "\050\036\052\037\054\040\001\001\000\004\047\045\001" +
    "\001\000\016\005\261\037\u0111\050\036\052\037\054\040" +
    "\055\260\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\005\261\037\270\040\u0114\050\036\052\037\054\040" +
    "\055\260\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\041\u0117\001\001\000\004\042\u0118\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\u011b\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\005\u012e\050\036\052" +
    "\037\054\040\001\001\000\004\047\045\001\001\000\002" +
    "\001\001\000\012\005\u0131\050\036\052\037\054\040\001" +
    "\001\000\004\047\045\001\001\000\002\001\001\000\012" +
    "\005\u0134\050\036\052\037\054\040\001\001\000\004\047" +
    "\045\001\001\000\002\001\001\000\012\005\u0137\050\036" +
    "\052\037\054\040\001\001\000\004\047\045\001\001\000" +
    "\002\001\001\000\012\005\u013a\050\036\052\037\054\040" +
    "\001\001\000\004\047\045\001\001\000\002\001\001\000" +
    "\012\005\u013d\050\036\052\037\054\040\001\001\000\004" +
    "\047\045\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserPKM$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserPKM$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserPKM$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Utils
    LexerPKM lex;
    private ArrayList<ErrorReport> syntaxErrors;

    // Parser and Lexer Connection
    public ParserPKM(LexerPKM lex) {
        super(lex);
        this.lex = lex;
        this.syntaxErrors = new ArrayList<>();
    }

    // Getters
    public LexerPKM getLexer() {
        return this.lex;
    }

    public ArrayList<ErrorReport> getSyntaxErrors() {
        return this.syntaxErrors;
    }

    // Overwrite error methods
    public void syntax_error(Symbol cur_token) {
        String symbol = symbl_name_from_id(cur_token.sym);
        String lexeme = "";
        if (cur_token.value != null) {
            lexeme = cur_token.value.toString();
        }
        Integer line = cur_token.left;
        Integer column = cur_token.right;
        StringBuilder description = new StringBuilder();

        if (expected_token_ids().isEmpty()) {
            description.append("No se esperaba ningun simbolo");
        } else {
            description.append("Se esperaba [");
            for (Integer expected_token_id : expected_token_ids()) {
                if (!symbl_name_from_id(expected_token_id).equals("error")) {
                    description.append(symbl_name_from_id(expected_token_id));
                    description.append(" ");
                }
            }
            description.append("]");
        }

        this.syntaxErrors.add(new ErrorReport(lexeme + "/" + symbol, line, column, "Sintactico", description.toString()));
    }

    public void report_error(String message, Object info) {
        String lexeme = "";
        String symbol = "";
        String  description = "";
        Integer column = -1;
        Integer line = -1;
        try {
            Symbol cur_token = (Symbol) info;
            symbol = symbl_name_from_id(cur_token.sym);
            line = cur_token.left;
            column = cur_token.right;
            if (cur_token != null) {
                lexeme = cur_token.value.toString();
            }
            if (message != null) {
                description = message;
            }

            this.syntaxErrors.add(new ErrorReport(lexeme + "/" + symbol, line, column, "Sintactico", description));
        } catch (Exception e) {
            this.syntaxErrors.add(new ErrorReport(lexeme + "/" + symbol, line, column, "Sintactico", message));
        }
    }

    public void unrecovered_syntax_error(Symbol cur_token) {
        this.syntaxErrors.add(new ErrorReport("", cur_token.left, cur_token.right, "Sintactico", "Error de sintaxis severo detectado, revise bien el codigo."));
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserPKM$actions {
  private final ParserPKM parser;

  /** Constructor */
  CUP$ParserPKM$actions(ParserPKM parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserPKM$do_action_part00000000(
    int                        CUP$ParserPKM$act_num,
    java_cup.runtime.lr_parser CUP$ParserPKM$parser,
    java.util.Stack            CUP$ParserPKM$stack,
    int                        CUP$ParserPKM$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserPKM$result;

      /* select the action based on the action number */
      switch (CUP$ParserPKM$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= fuente_entrada EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		RESULT = start_val;
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserPKM$parser.done_parsing();
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // fuente_entrada ::= SEPARADOR metadatos SEPARADOR contenido 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("fuente_entrada",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // metadatos ::= AUTHOR DOS_PUNTOS ID FECHA DOS_PUNTOS INPUT_FECHA HORA DOS_PUNTOS INPUT_HORA DESCRIPTION DOS_PUNTOS TEXTO TOTAL_SECCIONES DOS_PUNTOS operacion_matematica TOTAL_PREGUNTAS DOS_PUNTOS operacion_matematica ABIERTAS DOS_PUNTOS operacion_matematica DESPLEGABLES DOS_PUNTOS operacion_matematica SELECCION DOS_PUNTOS operacion_matematica MULTIPLES DOS_PUNTOS operacion_matematica 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("metadatos",1, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-29)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // contenido ::= contenido etiqueta 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("contenido",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // contenido ::= etiqueta 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("contenido",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // etiqueta ::= seccion 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("etiqueta",4, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // etiqueta ::= tabla 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("etiqueta",4, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // etiqueta ::= texto 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("etiqueta",4, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // etiqueta ::= pregunta 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("etiqueta",4, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // estilo ::= MENOR STYLE_ETIQUETA MAYOR contenido_estilo MENOR DIAGONAL STYLE_ETIQUETA MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("estilo",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // contenido_estilo ::= MENOR COLOR_ETIQUETA IGUAL color DIAGONAL MAYOR MENOR BACKGROUND_COLOR_ETIQUETA IGUAL color DIAGONAL MAYOR MENOR FONT_FAMILY_ETIQUETA IGUAL tipo_fuente DIAGONAL MAYOR MENOR TEXT_SIZE_ETIQUETA IGUAL operacion_matematica DIAGONAL MAYOR MENOR BORDER_ETIQUETA COMA operacion_matematica COMA tipo_borde COMA COLOR_ETIQUETA IGUAL color DIAGONAL MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("contenido_estilo",10, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-35)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // color ::= HEXADECIMAL 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color",11, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // color ::= rgb 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color",11, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // color ::= hsl 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color",11, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // color ::= color_literal 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color",11, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // rgb ::= PARENTESIS_ABIERTO operacion_matematica COMA operacion_matematica COMA operacion_matematica PARENTESIS_CERRADO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("rgb",14, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // hsl ::= MENOR operacion_matematica COMA operacion_matematica COMA operacion_matematica MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("hsl",15, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // color_literal ::= RED 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color_literal",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // color_literal ::= BLUE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color_literal",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // color_literal ::= GREEN 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color_literal",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // color_literal ::= PURPLE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color_literal",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // color_literal ::= SKY 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color_literal",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // color_literal ::= YELLOW 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color_literal",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // color_literal ::= BLACK 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color_literal",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // color_literal ::= WHITE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("color_literal",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo_fuente ::= MONO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_fuente",12, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo_fuente ::= SANS_SERIF 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_fuente",12, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo_fuente ::= CURSIVE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_fuente",12, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // tipo_borde ::= LINE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_borde",13, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipo_borde ::= DOTTED 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_borde",13, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // tipo_borde ::= DOUBLE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_borde",13, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // seccion ::= MENOR SECTION_ETIQUETA IGUAL operacion_matematica COMA operacion_matematica COMA operacion_matematica COMA operacion_matematica COMA tipo_orientacion MAYOR estilo MENOR CONTENT_ETIQUETA MAYOR lista_elemento MENOR DIAGONAL CONTENT_ETIQUETA MAYOR MENOR DIAGONAL SECTION_ETIQUETA MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("seccion",5, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-25)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // tipo_orientacion ::= VERTICAL 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_orientacion",17, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // tipo_orientacion ::= HORIZONTAL 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_orientacion",17, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_elemento ::= lista_elemento elemento 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_elemento",20, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // lista_elemento ::= elemento 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_elemento",20, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // elemento ::= seccion 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento",22, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // elemento ::= pregunta 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento",22, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // elemento ::= tabla 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento",22, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // elemento ::= texto 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento",22, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // lista_elemento_tabla ::= lista_elemento_tabla linea_tabla 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_elemento_tabla",21, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // lista_elemento_tabla ::= linea_tabla 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_elemento_tabla",21, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // linea_tabla ::= MENOR LINE_ETIQUETA MAYOR lista_elemento_linea MENOR DIAGONAL LINE_ETIQUETA MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("linea_tabla",23, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // lista_elemento_linea ::= lista_elemento_linea MENOR ELEMENT_ETIQUETA MAYOR elemento MENOR DIAGONAL ELEMENT_ETIQUETA MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_elemento_linea",24, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // lista_elemento_linea ::= MENOR ELEMENT_ETIQUETA MAYOR elemento MENOR DIAGONAL ELEMENT_ETIQUETA MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_elemento_linea",24, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // tabla ::= MENOR TABLE_ETIQUETA MAYOR estilo MENOR CONTENT_ETIQUETA MAYOR lista_elemento_tabla MENOR DIAGONAL CONTENT_ETIQUETA MAYOR MENOR DIAGONAL TABLE_ETIQUETA MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tabla",6, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-15)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // texto ::= MENOR OPEN_ETIQUETA IGUAL operacion_matematica COMA operacion_matematica COMA TEXTO cierre_etiqueta_texto 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("texto",7, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // cierre_etiqueta_texto ::= DIAGONAL MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("cierre_etiqueta_texto",25, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // cierre_etiqueta_texto ::= MAYOR estilo MENOR DIAGONAL OPEN_ETIQUETA MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("cierre_etiqueta_texto",25, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-5)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // pregunta ::= pregunta_desplegable 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("pregunta",8, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // pregunta ::= pregunta_seleccion_unica 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("pregunta",8, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // pregunta ::= pregunta_seleccion_multiple 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("pregunta",8, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // pregunta_desplegable ::= MENOR DROP_ETIQUETA IGUAL operacion_matematica COMA operacion_matematica COMA concatenacion_string COMA LLAVE_ABIERTO lista_opcion LLAVE_CERRADO COMA numero_entero cierre_etiqueta_pregunta_desplegable 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("pregunta_desplegable",26, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-14)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // lista_opcion ::= lista_opcion COMA concatenacion_string 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_opcion",30, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // lista_opcion ::= concatenacion_string 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_opcion",30, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // numero_entero ::= NUMERO_ENTERO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("numero_entero",31, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // numero_entero ::= NUMERO_ENTERO_NEGATIVO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("numero_entero",31, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // cierre_etiqueta_pregunta_desplegable ::= DIAGONAL MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("cierre_etiqueta_pregunta_desplegable",32, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // cierre_etiqueta_pregunta_desplegable ::= MAYOR estilo MENOR DIAGONAL DROP_ETIQUETA MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("cierre_etiqueta_pregunta_desplegable",32, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-5)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // pregunta_seleccion_unica ::= MENOR SELECT_ETIQUETA IGUAL operacion_matematica COMA operacion_matematica COMA concatenacion_string COMA LLAVE_ABIERTO lista_opcion LLAVE_CERRADO COMA numero_entero cierre_etiqueta_pregunta_seleccion_unica 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("pregunta_seleccion_unica",27, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-14)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // cierre_etiqueta_pregunta_seleccion_unica ::= DIAGONAL MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("cierre_etiqueta_pregunta_seleccion_unica",33, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // cierre_etiqueta_pregunta_seleccion_unica ::= MAYOR estilo MENOR DIAGONAL SELECT_ETIQUETA MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("cierre_etiqueta_pregunta_seleccion_unica",33, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-5)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // pregunta_seleccion_multiple ::= MENOR MULTIPLE_ETIQUETA IGUAL operacion_matematica COMA operacion_matematica COMA concatenacion_string COMA LLAVE_ABIERTO lista_opcion LLAVE_CERRADO COMA LLAVE_ABIERTO opcion_correcto LLAVE_CERRADO COMA cierre_etiqueta_pregunta_seleccion_multiple 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("pregunta_seleccion_multiple",28, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-17)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // opcion_correcto ::= lista_correcto 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("opcion_correcto",35, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // opcion_correcto ::= 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("opcion_correcto",35, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // lista_correcto ::= lista_correcto COMA operacion_matematica 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_correcto",36, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // lista_correcto ::= operacion_matematica 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_correcto",36, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // cierre_etiqueta_pregunta_seleccion_multiple ::= DIAGONAL MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("cierre_etiqueta_pregunta_seleccion_multiple",34, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // cierre_etiqueta_pregunta_seleccion_multiple ::= MAYOR estilo MENOR DIAGONAL MULTIPLE_ETIQUETA MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("cierre_etiqueta_pregunta_seleccion_multiple",34, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-5)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // operacion_matematica ::= operacion_matematica operador_sr t 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("operacion_matematica",3, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // operacion_matematica ::= t 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("operacion_matematica",3, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // t ::= t operador_md g 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("t",38, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // t ::= g 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("t",38, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // g ::= g operador_pm f 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("g",40, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // g ::= f 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("g",40, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // f ::= PARENTESIS_ABIERTO operacion_matematica PARENTESIS_CERRADO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("f",42, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // f ::= NUMERO_DECIMAL 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("f",42, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // f ::= NUMERO_ENTERO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("f",42, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // f ::= ID 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("f",42, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // operador_sr ::= SUMA 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("operador_sr",37, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // operador_sr ::= RESTA 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("operador_sr",37, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // operador_md ::= MULTIPLICACION 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("operador_md",39, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // operador_md ::= DIVISION 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("operador_md",39, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // operador_pm ::= POTENCIA 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("operador_pm",41, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // operador_pm ::= MODULO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("operador_pm",41, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // concatenacion_string ::= concatenacion_string SUMA operacion_string 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("concatenacion_string",29, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // concatenacion_string ::= operacion_string 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("concatenacion_string",29, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // operacion_string ::= TEXTO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("operacion_string",43, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // operacion_string ::= operacion_matematica 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("operacion_string",43, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserPKM$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserPKM$do_action(
    int                        CUP$ParserPKM$act_num,
    java_cup.runtime.lr_parser CUP$ParserPKM$parser,
    java.util.Stack            CUP$ParserPKM$stack,
    int                        CUP$ParserPKM$top)
    throws java.lang.Exception
    {
              return CUP$ParserPKM$do_action_part00000000(
                               CUP$ParserPKM$act_num,
                               CUP$ParserPKM$parser,
                               CUP$ParserPKM$stack,
                               CUP$ParserPKM$top);
    }
}

}
