// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/com/example/proyecto1_compi1_ps26/domain/analyzers/form_creation/LexerForm.flex

// IMPORTS
package com.example.proyecto1_compi1_ps26.domain.analyzers.form_creation;

import java_cup.runtime.*;
import com.example.proyecto1_compi1_ps26.domain.analyzers.form_creation.symForm;

import java.util.ArrayList;

import com.example.proyecto1_compi1_ps26.domain.entities.ErrorReport;


@SuppressWarnings("fallthrough")
public class LexerForm implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int TEXT = 2;
  public static final int SIMPLE_COMMENT = 4;
  public static final int MULTIPLE_COMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\0\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\11\25\1\26\1\27\1\30\1\31\1\32\1\33\1\0"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\0\1\67\1\70\1\71\1\0"+
    "\1\72\1\73\1\74\1\75\1\76\1\77\1\100\1\101"+
    "\1\102\1\45\1\103\1\104\1\105\1\106\1\107\1\110"+
    "\1\45\1\111\1\112\1\113\1\114\1\45\1\115\1\116"+
    "\1\117\1\120\1\121\1\122\1\123\1\124\6\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\1\1\3\1\1\1\4\1\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\2\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\24\25\1\26\1\27\1\30\1\1\13\25\1\31\1\1"+
    "\1\32\1\33\1\34\2\35\1\36\1\34\2\37\1\34"+
    "\1\40\5\0\1\41\1\42\1\0\1\43\1\44\1\45"+
    "\2\25\1\46\5\25\1\47\23\25\1\50\11\25\1\51"+
    "\1\52\6\0\1\53\7\25\1\54\10\25\1\55\3\25"+
    "\1\56\24\25\5\0\1\57\1\25\1\60\4\25\1\61"+
    "\2\25\1\62\1\63\10\25\1\64\6\25\1\65\14\25"+
    "\6\0\1\66\4\25\1\67\10\25\1\70\1\25\1\71"+
    "\1\72\5\25\1\73\10\25\1\74\6\0\1\25\1\75"+
    "\1\76\3\25\1\77\1\25\1\100\4\25\1\101\3\25"+
    "\1\102\1\103\2\25\1\104\1\105\1\25\1\106\1\107"+
    "\1\25\2\0\1\110\2\0\1\57\1\111\5\25\1\112"+
    "\2\25\1\113\1\114\1\25\1\115\1\25\1\116\1\25"+
    "\1\0\1\117\2\0\6\25\1\120\1\121\2\25\3\0"+
    "\10\25\3\0\1\25\1\122\2\25\1\123\3\25\2\0"+
    "\1\124\4\25\1\125\1\25\2\0\5\25\1\0\1\126"+
    "\1\127\1\25\1\130\2\25\1\0\3\25\1\0\1\25"+
    "\1\131\1\25\1\0\2\25\1\0\1\132\1\25\1\133"+
    "\1\25\1\134";

  private static int [] zzUnpackAction() {
    int [] result = new int[391];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\125\0\252\0\377\0\u0154\0\u0154\0\u01a9\0\u01fe"+
    "\0\u0253\0\u02a8\0\u0154\0\u0154\0\u02fd\0\u0154\0\u0154\0\u0154"+
    "\0\u0154\0\u0154\0\u0154\0\u0154\0\u0352\0\u03a7\0\u03fc\0\u0154"+
    "\0\u0154\0\u0451\0\u04a6\0\u04fb\0\u0154\0\u0550\0\u05a5\0\u05fa"+
    "\0\u064f\0\u06a4\0\u06f9\0\u074e\0\u07a3\0\u07f8\0\u084d\0\u08a2"+
    "\0\u08f7\0\u094c\0\u09a1\0\u09f6\0\u0a4b\0\u0aa0\0\u0af5\0\u0b4a"+
    "\0\u0b9f\0\u0154\0\u0154\0\u0154\0\u0bf4\0\u0c49\0\u0c9e\0\u0cf3"+
    "\0\u0d48\0\u0d9d\0\u0df2\0\u0e47\0\u0e9c\0\u0ef1\0\u0f46\0\u0f9b"+
    "\0\u0154\0\u0ff0\0\u0154\0\u0154\0\u0154\0\u0154\0\u1045\0\u0154"+
    "\0\u109a\0\u0154\0\u10ef\0\u1144\0\u0154\0\u1199\0\u11ee\0\u1243"+
    "\0\u1298\0\u12ed\0\u0154\0\u0154\0\u1342\0\u0154\0\u0154\0\u0154"+
    "\0\u1397\0\u13ec\0\u1441\0\u1496\0\u14eb\0\u1540\0\u1595\0\u15ea"+
    "\0\u0550\0\u163f\0\u1694\0\u16e9\0\u173e\0\u1793\0\u17e8\0\u183d"+
    "\0\u1892\0\u18e7\0\u193c\0\u1991\0\u19e6\0\u1a3b\0\u1a90\0\u1ae5"+
    "\0\u1b3a\0\u1b8f\0\u1be4\0\u1c39\0\u0550\0\u1c8e\0\u1ce3\0\u1d38"+
    "\0\u1d8d\0\u1de2\0\u1e37\0\u1e8c\0\u1ee1\0\u1f36\0\u0154\0\u0154"+
    "\0\u1f8b\0\u1fe0\0\u2035\0\u208a\0\u20df\0\u2134\0\u1342\0\u2189"+
    "\0\u21de\0\u2233\0\u2288\0\u22dd\0\u2332\0\u2387\0\u0550\0\u23dc"+
    "\0\u2431\0\u2486\0\u24db\0\u2530\0\u2585\0\u25da\0\u262f\0\u0550"+
    "\0\u2684\0\u26d9\0\u272e\0\u0550\0\u2783\0\u27d8\0\u282d\0\u2882"+
    "\0\u28d7\0\u292c\0\u2981\0\u29d6\0\u2a2b\0\u2a80\0\u2ad5\0\u2b2a"+
    "\0\u2b7f\0\u2bd4\0\u2c29\0\u2c7e\0\u2cd3\0\u2d28\0\u2d7d\0\u2dd2"+
    "\0\u2e27\0\u2e7c\0\u2ed1\0\u2f26\0\u2f7b\0\u2fd0\0\u3025\0\u0550"+
    "\0\u307a\0\u30cf\0\u3124\0\u3179\0\u0550\0\u31ce\0\u3223\0\u0550"+
    "\0\u0550\0\u3278\0\u32cd\0\u3322\0\u3377\0\u33cc\0\u3421\0\u3476"+
    "\0\u34cb\0\u0550\0\u3520\0\u3575\0\u35ca\0\u361f\0\u3674\0\u36c9"+
    "\0\u0550\0\u371e\0\u3773\0\u37c8\0\u381d\0\u3872\0\u38c7\0\u391c"+
    "\0\u3971\0\u39c6\0\u3a1b\0\u3a70\0\u3ac5\0\u3b1a\0\u3b6f\0\u3bc4"+
    "\0\u3c19\0\u3c6e\0\u3cc3\0\u0550\0\u3d18\0\u3d6d\0\u3dc2\0\u3e17"+
    "\0\u0550\0\u3e6c\0\u3ec1\0\u3f16\0\u3f6b\0\u3fc0\0\u4015\0\u406a"+
    "\0\u40bf\0\u0550\0\u4114\0\u0550\0\u0550\0\u4169\0\u41be\0\u4213"+
    "\0\u4268\0\u42bd\0\u0550\0\u4312\0\u4367\0\u43bc\0\u4411\0\u4466"+
    "\0\u44bb\0\u4510\0\u4565\0\u0550\0\u45ba\0\u460f\0\u4664\0\u46b9"+
    "\0\u470e\0\u4763\0\u47b8\0\u0550\0\u0550\0\u480d\0\u4862\0\u48b7"+
    "\0\u0550\0\u490c\0\u0550\0\u4961\0\u49b6\0\u4a0b\0\u4a60\0\u0550"+
    "\0\u4ab5\0\u4b0a\0\u4b5f\0\u0550\0\u0550\0\u4bb4\0\u4c09\0\u0550"+
    "\0\u0550\0\u4c5e\0\u0550\0\u0550\0\u4cb3\0\u4d08\0\u4d5d\0\u0154"+
    "\0\u4db2\0\u4e07\0\u0154\0\u0550\0\u4e5c\0\u4eb1\0\u4f06\0\u4f5b"+
    "\0\u4fb0\0\u0550\0\u5005\0\u505a\0\u0550\0\u0550\0\u50af\0\u0550"+
    "\0\u5104\0\u0550\0\u5159\0\u51ae\0\u0154\0\u5203\0\u5258\0\u52ad"+
    "\0\u5302\0\u5357\0\u53ac\0\u5401\0\u5456\0\u0550\0\u0550\0\u54ab"+
    "\0\u5500\0\u5555\0\u55aa\0\u55ff\0\u5654\0\u56a9\0\u56fe\0\u5753"+
    "\0\u57a8\0\u57fd\0\u5852\0\u58a7\0\u58fc\0\u5951\0\u59a6\0\u59fb"+
    "\0\u0550\0\u5a50\0\u5aa5\0\u0550\0\u5afa\0\u5b4f\0\u5ba4\0\u5bf9"+
    "\0\u5c4e\0\u0154\0\u5ca3\0\u5cf8\0\u5d4d\0\u5da2\0\u0550\0\u5df7"+
    "\0\u5e4c\0\u5ea1\0\u5ef6\0\u5f4b\0\u5fa0\0\u5ff5\0\u604a\0\u609f"+
    "\0\u0154\0\u0550\0\u60f4\0\u0550\0\u6149\0\u619e\0\u61f3\0\u6248"+
    "\0\u629d\0\u62f2\0\u6347\0\u639c\0\u0550\0\u63f1\0\u6446\0\u649b"+
    "\0\u64f0\0\u6545\0\u0550\0\u659a\0\u0154\0\u65ef\0\u0550";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[391];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\0\1\7\1\6\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\2\36\1\47\1\50\1\51"+
    "\1\52\1\53\1\36\1\54\1\55\1\56\1\36\1\57"+
    "\1\60\1\36\1\61\1\36\1\62\1\63\1\64\1\65"+
    "\2\36\1\66\1\67\1\70\2\36\1\71\1\72\1\36"+
    "\1\73\1\36\1\74\1\75\1\76\1\36\1\77\2\36"+
    "\1\100\3\36\1\101\1\102\1\103\1\104\2\105\1\106"+
    "\1\105\1\107\2\105\1\110\115\105\2\111\1\112\1\111"+
    "\1\113\120\111\2\105\1\6\1\105\1\7\11\105\1\114"+
    "\106\105\127\0\1\6\130\0\1\115\211\0\1\116\1\117"+
    "\2\0\1\120\13\0\1\121\35\0\2\122\6\0\6\122"+
    "\30\0\6\122\40\0\1\123\127\0\1\124\130\0\1\125"+
    "\124\0\1\125\1\0\2\27\130\0\1\126\124\0\1\127"+
    "\124\0\1\130\117\0\2\36\6\0\32\36\3\0\30\36"+
    "\30\0\2\36\6\0\13\36\1\131\16\36\3\0\30\36"+
    "\30\0\2\36\6\0\24\36\1\132\5\36\3\0\30\36"+
    "\30\0\2\36\6\0\16\36\1\133\2\36\1\134\10\36"+
    "\3\0\30\36\30\0\2\36\6\0\13\36\1\135\16\36"+
    "\3\0\30\36\30\0\2\36\6\0\16\36\1\136\13\36"+
    "\3\0\30\36\30\0\2\36\6\0\21\36\1\137\10\36"+
    "\3\0\30\36\30\0\2\36\6\0\16\36\1\140\13\36"+
    "\3\0\30\36\30\0\2\36\6\0\5\36\1\141\24\36"+
    "\3\0\30\36\30\0\2\36\6\0\10\36\1\142\21\36"+
    "\3\0\30\36\30\0\2\36\6\0\16\36\1\143\5\36"+
    "\1\144\5\36\3\0\30\36\30\0\2\36\6\0\24\36"+
    "\1\145\5\36\3\0\30\36\30\0\2\36\6\0\17\36"+
    "\1\146\12\36\3\0\30\36\30\0\2\36\6\0\24\36"+
    "\1\147\5\36\3\0\30\36\30\0\2\36\6\0\4\36"+
    "\1\150\25\36\3\0\30\36\30\0\2\36\6\0\1\151"+
    "\3\36\1\152\5\36\1\153\17\36\3\0\30\36\30\0"+
    "\2\36\6\0\1\154\3\36\1\155\25\36\3\0\30\36"+
    "\30\0\2\36\6\0\4\36\1\156\25\36\3\0\30\36"+
    "\30\0\2\36\6\0\7\36\1\157\22\36\3\0\30\36"+
    "\30\0\2\36\6\0\4\36\1\160\25\36\3\0\30\36"+
    "\40\0\32\36\4\0\27\36\30\0\2\36\6\0\32\36"+
    "\3\0\16\36\1\161\11\36\30\0\2\36\6\0\32\36"+
    "\3\0\20\36\1\162\7\36\30\0\2\36\6\0\32\36"+
    "\3\0\13\36\1\163\14\36\30\0\2\36\6\0\32\36"+
    "\3\0\5\36\1\164\22\36\30\0\2\36\6\0\32\36"+
    "\3\0\15\36\1\165\12\36\30\0\2\36\6\0\32\36"+
    "\3\0\1\36\1\166\26\36\30\0\2\36\6\0\32\36"+
    "\3\0\23\36\1\167\4\36\30\0\2\36\6\0\32\36"+
    "\3\0\17\36\1\170\1\171\7\36\30\0\2\36\6\0"+
    "\32\36\3\0\16\36\1\172\11\36\30\0\2\36\6\0"+
    "\32\36\3\0\17\36\1\173\2\36\1\174\5\36\30\0"+
    "\2\36\6\0\32\36\3\0\10\36\1\175\1\176\16\36"+
    "\126\0\1\177\4\0\1\106\122\0\2\111\1\0\1\111"+
    "\1\0\120\111\2\0\1\112\145\0\1\200\173\0\1\201"+
    "\14\0\1\202\124\0\1\203\124\0\1\204\113\0\1\205"+
    "\52\0\2\206\6\0\6\206\30\0\6\206\51\0\2\207"+
    "\123\0\2\36\6\0\1\210\23\36\1\211\5\36\3\0"+
    "\30\36\30\0\2\36\6\0\21\36\1\212\10\36\3\0"+
    "\30\36\30\0\2\36\6\0\23\36\1\213\1\214\5\36"+
    "\3\0\30\36\30\0\2\36\6\0\16\36\1\215\13\36"+
    "\3\0\30\36\30\0\2\36\6\0\22\36\1\216\7\36"+
    "\3\0\30\36\30\0\2\36\6\0\21\36\1\217\10\36"+
    "\3\0\30\36\30\0\2\36\6\0\4\36\1\220\25\36"+
    "\3\0\30\36\30\0\2\36\6\0\21\36\1\221\10\36"+
    "\3\0\30\36\30\0\2\36\6\0\15\36\1\222\14\36"+
    "\3\0\30\36\30\0\2\36\6\0\15\36\1\223\14\36"+
    "\3\0\30\36\30\0\2\36\6\0\13\36\1\224\16\36"+
    "\3\0\30\36\30\0\2\36\6\0\14\36\1\225\15\36"+
    "\3\0\30\36\30\0\2\36\6\0\4\36\1\226\25\36"+
    "\3\0\30\36\30\0\2\36\6\0\21\36\1\227\10\36"+
    "\3\0\30\36\30\0\2\36\6\0\3\36\1\230\26\36"+
    "\3\0\30\36\30\0\2\36\6\0\15\36\1\231\14\36"+
    "\3\0\30\36\30\0\2\36\6\0\2\36\1\232\10\36"+
    "\1\233\16\36\3\0\30\36\30\0\2\36\6\0\30\36"+
    "\1\234\1\36\3\0\30\36\30\0\2\36\6\0\1\36"+
    "\1\235\30\36\3\0\30\36\30\0\2\36\6\0\27\36"+
    "\1\236\2\36\3\0\30\36\30\0\2\36\6\0\21\36"+
    "\1\237\10\36\3\0\30\36\30\0\2\36\6\0\10\36"+
    "\1\240\21\36\3\0\30\36\30\0\2\36\6\0\13\36"+
    "\1\241\16\36\3\0\30\36\30\0\2\36\6\0\32\36"+
    "\3\0\15\36\1\242\2\36\1\243\7\36\30\0\2\36"+
    "\6\0\32\36\3\0\1\36\1\244\26\36\30\0\2\36"+
    "\6\0\32\36\3\0\5\36\1\245\22\36\30\0\2\36"+
    "\6\0\32\36\3\0\11\36\1\246\16\36\30\0\2\36"+
    "\6\0\32\36\3\0\2\36\1\247\25\36\30\0\2\36"+
    "\6\0\32\36\3\0\14\36\1\250\13\36\30\0\2\36"+
    "\6\0\32\36\3\0\22\36\1\251\5\36\30\0\2\36"+
    "\6\0\32\36\3\0\11\36\1\252\16\36\30\0\2\36"+
    "\6\0\32\36\3\0\11\36\1\253\16\36\30\0\2\36"+
    "\6\0\32\36\3\0\5\36\1\254\22\36\30\0\2\36"+
    "\6\0\32\36\3\0\20\36\1\255\5\36\1\256\1\36"+
    "\30\0\2\36\6\0\32\36\3\0\16\36\1\257\11\36"+
    "\30\0\2\36\6\0\32\36\3\0\4\36\1\260\23\36"+
    "\100\0\1\261\141\0\1\262\117\0\1\263\126\0\1\264"+
    "\134\0\1\265\32\0\2\266\6\0\6\266\30\0\6\266"+
    "\51\0\2\36\6\0\2\36\1\267\27\36\3\0\30\36"+
    "\30\0\2\36\6\0\4\36\1\270\25\36\3\0\30\36"+
    "\30\0\2\36\6\0\22\36\1\271\7\36\3\0\30\36"+
    "\30\0\2\36\6\0\23\36\1\272\6\36\3\0\30\36"+
    "\30\0\2\36\6\0\1\36\1\273\30\36\3\0\30\36"+
    "\30\0\2\36\6\0\17\36\1\274\12\36\3\0\30\36"+
    "\30\0\2\36\6\0\4\36\1\275\25\36\3\0\30\36"+
    "\30\0\2\36\6\0\4\36\1\276\25\36\3\0\30\36"+
    "\30\0\2\36\6\0\10\36\1\277\21\36\3\0\30\36"+
    "\30\0\2\36\6\0\4\36\1\300\25\36\3\0\30\36"+
    "\30\0\2\36\6\0\16\36\1\301\13\36\3\0\30\36"+
    "\30\0\2\36\6\0\23\36\1\302\6\36\3\0\30\36"+
    "\30\0\2\36\6\0\1\36\1\303\30\36\3\0\30\36"+
    "\30\0\2\36\6\0\15\36\1\304\14\36\3\0\30\36"+
    "\30\0\2\36\6\0\17\36\1\305\12\36\3\0\30\36"+
    "\30\0\2\36\6\0\22\36\1\306\7\36\3\0\30\36"+
    "\30\0\2\36\6\0\23\36\1\307\6\36\3\0\30\36"+
    "\30\0\2\36\6\0\4\36\1\310\25\36\3\0\30\36"+
    "\30\0\2\36\6\0\13\36\1\311\16\36\3\0\30\36"+
    "\30\0\2\36\6\0\23\36\1\312\6\36\3\0\30\36"+
    "\30\0\2\36\6\0\23\36\1\313\6\36\3\0\30\36"+
    "\30\0\2\36\6\0\13\36\1\314\7\36\1\315\6\36"+
    "\3\0\30\36\30\0\2\36\6\0\13\36\1\316\16\36"+
    "\3\0\30\36\30\0\2\36\6\0\32\36\3\0\22\36"+
    "\1\317\5\36\30\0\2\36\6\0\32\36\3\0\20\36"+
    "\1\320\7\36\30\0\2\36\6\0\32\36\3\0\24\36"+
    "\1\321\3\36\30\0\2\36\6\0\32\36\3\0\14\36"+
    "\1\322\13\36\30\0\2\36\6\0\32\36\3\0\7\36"+
    "\1\323\20\36\30\0\2\36\6\0\32\36\3\0\5\36"+
    "\1\324\22\36\30\0\2\36\6\0\32\36\3\0\2\36"+
    "\1\325\25\36\30\0\2\36\6\0\32\36\3\0\11\36"+
    "\1\326\16\36\30\0\2\36\6\0\32\36\3\0\5\36"+
    "\1\327\22\36\30\0\2\36\6\0\32\36\3\0\15\36"+
    "\1\330\12\36\30\0\2\36\6\0\32\36\3\0\3\36"+
    "\1\331\24\36\30\0\2\36\6\0\32\36\3\0\11\36"+
    "\1\332\16\36\30\0\2\36\6\0\32\36\3\0\13\36"+
    "\1\333\14\36\30\0\2\36\6\0\32\36\3\0\1\334"+
    "\27\36\30\0\2\36\6\0\32\36\3\0\22\36\1\335"+
    "\5\36\107\0\1\336\116\0\1\337\136\0\1\340\130\0"+
    "\1\341\124\0\1\342\35\0\2\343\6\0\6\343\30\0"+
    "\6\343\51\0\2\36\6\0\12\36\1\344\17\36\3\0"+
    "\30\36\30\0\2\36\6\0\10\36\1\345\21\36\3\0"+
    "\30\36\30\0\2\36\6\0\4\36\1\346\25\36\3\0"+
    "\30\36\30\0\2\36\6\0\13\36\1\347\16\36\3\0"+
    "\30\36\30\0\2\36\6\0\32\36\3\0\1\350\27\36"+
    "\30\0\2\36\6\0\15\36\1\351\14\36\3\0\30\36"+
    "\30\0\2\36\6\0\31\36\1\352\3\0\30\36\30\0"+
    "\2\36\6\0\10\36\1\353\21\36\3\0\30\36\30\0"+
    "\2\36\6\0\4\36\1\354\25\36\3\0\30\36\30\0"+
    "\2\36\6\0\32\36\3\0\1\355\27\36\30\0\2\36"+
    "\6\0\13\36\1\356\16\36\3\0\30\36\30\0\2\36"+
    "\6\0\32\36\3\0\1\357\27\36\30\0\2\36\6\0"+
    "\10\36\1\360\21\36\3\0\30\36\30\0\2\36\6\0"+
    "\2\36\1\361\27\36\3\0\30\36\30\0\2\36\6\0"+
    "\4\36\1\362\25\36\3\0\30\36\30\0\2\36\6\0"+
    "\10\36\1\363\21\36\3\0\30\36\30\0\2\36\6\0"+
    "\4\36\1\364\25\36\3\0\30\36\30\0\2\36\6\0"+
    "\4\36\1\365\25\36\3\0\30\36\30\0\2\36\6\0"+
    "\16\36\1\366\13\36\3\0\30\36\30\0\2\36\6\0"+
    "\32\36\3\0\5\36\1\367\22\36\30\0\2\36\6\0"+
    "\32\36\3\0\5\36\1\370\22\36\30\0\2\36\6\0"+
    "\32\36\3\0\5\36\1\371\22\36\30\0\2\36\6\0"+
    "\32\36\3\0\10\36\1\372\17\36\30\0\2\36\6\0"+
    "\32\36\3\0\13\36\1\373\14\36\30\0\2\36\6\0"+
    "\32\36\3\0\5\36\1\374\22\36\30\0\2\36\6\0"+
    "\32\36\3\0\16\36\1\375\11\36\30\0\2\36\6\0"+
    "\32\36\3\0\15\36\1\376\12\36\30\0\2\36\6\0"+
    "\32\36\3\0\22\36\1\377\5\36\30\0\2\36\6\0"+
    "\32\36\3\0\11\36\1\u0100\16\36\30\0\2\36\6\0"+
    "\32\36\3\0\15\36\1\u0101\12\36\30\0\2\36\6\0"+
    "\32\36\3\0\5\36\1\u0102\22\36\30\0\2\36\6\0"+
    "\32\36\3\0\11\36\1\u0103\16\36\30\0\2\36\6\0"+
    "\32\36\3\0\10\36\1\u0104\17\36\104\0\1\u0105\122\0"+
    "\1\u0106\137\0\1\u0107\20\0\1\u0108\124\0\1\u0109\143\0"+
    "\2\u010a\6\0\6\u010a\30\0\6\u010a\51\0\2\36\6\0"+
    "\25\36\1\u010b\4\36\3\0\30\36\30\0\2\36\6\0"+
    "\3\36\1\u010c\26\36\3\0\30\36\30\0\2\36\6\0"+
    "\4\36\1\u010d\25\36\3\0\30\36\30\0\2\36\6\0"+
    "\20\36\1\u010e\11\36\3\0\30\36\30\0\2\36\6\0"+
    "\16\36\1\u010f\13\36\3\0\30\36\30\0\2\36\6\0"+
    "\17\36\1\u0110\12\36\3\0\30\36\30\0\2\36\6\0"+
    "\21\36\1\u0111\10\36\3\0\30\36\30\0\2\36\6\0"+
    "\20\36\1\u0112\11\36\3\0\30\36\30\0\2\36\6\0"+
    "\4\36\1\u0113\25\36\3\0\30\36\30\0\2\36\6\0"+
    "\22\36\1\u0114\7\36\3\0\30\36\30\0\2\36\6\0"+
    "\16\36\1\u0115\13\36\3\0\30\36\30\0\2\36\6\0"+
    "\23\36\1\u0116\6\36\3\0\30\36\30\0\2\36\6\0"+
    "\2\36\1\u0117\27\36\3\0\30\36\30\0\2\36\6\0"+
    "\26\36\1\u0118\3\36\3\0\30\36\30\0\2\36\6\0"+
    "\32\36\3\0\15\36\1\u0119\12\36\30\0\2\36\6\0"+
    "\32\36\3\0\3\36\1\u011a\24\36\30\0\2\36\6\0"+
    "\32\36\3\0\15\36\1\u011b\12\36\30\0\2\36\6\0"+
    "\32\36\3\0\22\36\1\u011c\5\36\30\0\2\36\6\0"+
    "\32\36\3\0\20\36\1\u011d\7\36\30\0\2\36\6\0"+
    "\32\36\3\0\15\36\1\u011e\12\36\30\0\2\36\6\0"+
    "\32\36\3\0\22\36\1\u011f\5\36\30\0\2\36\6\0"+
    "\27\36\1\u0120\1\u0121\1\36\3\0\30\36\30\0\2\36"+
    "\6\0\32\36\3\0\1\36\1\u0122\26\36\30\0\2\36"+
    "\6\0\32\36\3\0\7\36\1\u0123\20\36\30\0\2\36"+
    "\6\0\32\36\3\0\21\36\1\u0124\6\36\30\0\2\36"+
    "\6\0\32\36\3\0\21\36\1\u0125\6\36\115\0\1\u0126"+
    "\124\0\1\u0127\22\0\1\u0128\214\0\1\u0129\137\0\1\u012a"+
    "\36\0\2\u012b\6\0\6\u012b\30\0\6\u012b\51\0\2\36"+
    "\6\0\4\36\1\u012c\25\36\3\0\30\36\30\0\2\36"+
    "\6\0\24\36\1\u012d\5\36\3\0\30\36\30\0\2\36"+
    "\6\0\15\36\1\u012e\14\36\3\0\30\36\30\0\2\36"+
    "\6\0\13\36\1\u012f\16\36\3\0\30\36\30\0\2\36"+
    "\6\0\24\36\1\u0130\5\36\3\0\30\36\30\0\2\36"+
    "\6\0\4\36\1\u0131\25\36\3\0\30\36\30\0\2\36"+
    "\6\0\15\36\1\u0132\14\36\3\0\30\36\30\0\2\36"+
    "\6\0\32\36\3\0\1\u0133\27\36\30\0\2\36\6\0"+
    "\1\u0134\31\36\3\0\30\36\30\0\2\36\6\0\32\36"+
    "\3\0\22\36\1\u0135\5\36\30\0\2\36\6\0\32\36"+
    "\3\0\22\36\1\u0136\5\36\30\0\2\36\6\0\32\36"+
    "\3\0\22\36\1\u0137\5\36\30\0\2\36\6\0\32\36"+
    "\3\0\21\36\1\u0138\6\36\30\0\2\36\6\0\32\36"+
    "\3\0\1\36\1\u0139\26\36\30\0\2\36\6\0\32\36"+
    "\3\0\13\36\1\u013a\14\36\30\0\2\36\6\0\32\36"+
    "\3\0\1\u013b\27\36\113\0\1\u013c\24\0\1\u013d\207\0"+
    "\1\u013e\134\0\1\u013f\46\0\2\36\6\0\4\36\1\u0140"+
    "\25\36\3\0\30\36\30\0\2\36\6\0\23\36\1\u0141"+
    "\6\36\3\0\30\36\30\0\2\36\6\0\4\36\1\u0142"+
    "\25\36\3\0\30\36\30\0\2\36\6\0\4\36\1\u0143"+
    "\25\36\3\0\30\36\30\0\2\36\6\0\21\36\1\u0144"+
    "\10\36\3\0\30\36\30\0\2\36\6\0\20\36\1\u0145"+
    "\11\36\3\0\30\36\30\0\2\36\6\0\13\36\1\u0146"+
    "\16\36\3\0\30\36\30\0\2\36\6\0\32\36\3\0"+
    "\21\36\1\u0147\6\36\30\0\2\36\6\0\32\36\3\0"+
    "\22\36\1\u0148\5\36\30\0\2\36\6\0\32\36\3\0"+
    "\22\36\1\u0149\5\36\120\0\1\u014a\115\0\1\u014b\137\0"+
    "\1\u014c\30\0\2\36\6\0\22\36\1\u014d\7\36\3\0"+
    "\30\36\30\0\2\36\6\0\1\u014e\31\36\3\0\30\36"+
    "\30\0\2\36\6\0\32\36\3\0\1\u014f\27\36\30\0"+
    "\2\36\6\0\22\36\1\u0150\7\36\3\0\30\36\30\0"+
    "\2\36\6\0\10\36\1\u0151\21\36\3\0\30\36\30\0"+
    "\2\36\6\0\24\36\1\u0152\5\36\3\0\30\36\30\0"+
    "\2\36\6\0\32\36\3\0\11\36\1\u0153\16\36\30\0"+
    "\2\36\6\0\32\36\3\0\10\36\1\u0154\17\36\112\0"+
    "\1\u0155\120\0\1\u0156\120\0\1\u0157\52\0\2\36\6\0"+
    "\23\36\1\u0158\6\36\3\0\30\36\30\0\2\36\6\0"+
    "\13\36\1\u0159\16\36\3\0\30\36\30\0\2\36\6\0"+
    "\20\36\1\u015a\11\36\3\0\30\36\30\0\2\36\6\0"+
    "\23\36\1\u015b\6\36\3\0\30\36\30\0\2\36\6\0"+
    "\5\36\1\u015c\24\36\3\0\30\36\30\0\2\36\6\0"+
    "\4\36\1\u015d\25\36\3\0\30\36\30\0\2\36\6\0"+
    "\32\36\3\0\16\36\1\u015e\11\36\30\0\2\36\6\0"+
    "\32\36\3\0\1\36\1\u015f\26\36\101\0\1\u0160\133\0"+
    "\1\u0161\27\0\1\u0162\141\0\2\36\6\0\10\36\1\u0163"+
    "\21\36\3\0\30\36\30\0\2\36\6\0\24\36\1\u0164"+
    "\5\36\3\0\30\36\30\0\2\36\6\0\10\36\1\u0165"+
    "\21\36\3\0\30\36\30\0\2\36\6\0\22\36\1\u0166"+
    "\7\36\3\0\30\36\30\0\2\36\6\0\32\36\3\0"+
    "\15\36\1\u0167\12\36\30\0\2\36\6\0\32\36\3\0"+
    "\22\36\1\u0168\5\36\11\0\1\u0169\236\0\1\u016a\31\0"+
    "\2\36\6\0\16\36\1\u016b\13\36\3\0\30\36\30\0"+
    "\2\36\6\0\4\36\1\u016c\25\36\3\0\30\36\30\0"+
    "\2\36\6\0\16\36\1\u016d\13\36\3\0\30\36\30\0"+
    "\2\36\6\0\23\36\1\u016e\6\36\3\0\30\36\30\0"+
    "\2\36\6\0\32\36\3\0\1\u016f\27\36\100\0\1\u0170"+
    "\37\0\1\u0171\141\0\2\36\6\0\15\36\1\u0172\14\36"+
    "\3\0\30\36\30\0\2\36\6\0\22\36\1\u0173\7\36"+
    "\3\0\30\36\30\0\2\36\6\0\15\36\1\u0174\14\36"+
    "\3\0\30\36\30\0\2\36\6\0\10\36\1\u0175\21\36"+
    "\3\0\30\36\30\0\2\36\6\0\32\36\3\0\17\36"+
    "\1\u0176\10\36\113\0\1\u0177\41\0\2\36\6\0\23\36"+
    "\1\u0178\6\36\3\0\30\36\30\0\2\36\6\0\16\36"+
    "\1\u0179\13\36\3\0\30\36\30\0\2\36\6\0\32\36"+
    "\3\0\16\36\1\u017a\11\36\110\0\1\u017b\44\0\2\36"+
    "\6\0\10\36\1\u017c\21\36\3\0\30\36\30\0\2\36"+
    "\6\0\15\36\1\u017d\14\36\3\0\30\36\30\0\2\36"+
    "\6\0\32\36\3\0\12\36\1\u017e\15\36\113\0\1\u017f"+
    "\41\0\2\36\6\0\16\36\1\u0180\13\36\3\0\30\36"+
    "\30\0\2\36\6\0\32\36\3\0\5\36\1\u0181\22\36"+
    "\115\0\1\u0182\37\0\2\36\6\0\15\36\1\u0183\14\36"+
    "\3\0\30\36\30\0\2\36\6\0\32\36\3\0\14\36"+
    "\1\u0184\13\36\13\0\1\u0185\141\0\2\36\6\0\32\36"+
    "\3\0\16\36\1\u0186\11\36\30\0\2\36\6\0\32\36"+
    "\3\0\15\36\1\u0187\12\36\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[26180];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\4\1\2\11\1\1\7\11\3\1\2\11"+
    "\3\1\1\11\24\1\3\11\14\1\1\11\1\1\4\11"+
    "\1\1\1\11\1\1\1\11\2\1\1\11\5\0\2\11"+
    "\1\0\3\11\46\1\2\11\6\0\52\1\5\0\50\1"+
    "\6\0\41\1\6\0\33\1\2\0\1\11\2\0\1\11"+
    "\20\1\1\0\1\11\2\0\12\1\3\0\10\1\3\0"+
    "\10\1\2\0\1\11\6\1\2\0\5\1\1\0\1\11"+
    "\5\1\1\0\3\1\1\0\3\1\1\0\2\1\1\0"+
    "\2\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[391];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // Utils
    private StringBuilder string;

    // Error Handling
    private ArrayList<String> symbols;
    private ArrayList<ErrorReport> lexicalErrors;

    private void error(String token) {
        this.lexicalErrors.add(new ErrorReport(token, yyline, yycolumn, "Lexico", "Cadena no existente en el lenguaje"));
    }

    public ArrayList<ErrorReport> getLexicalErrors(){
        return this.lexicalErrors;
    }

    public ArrayList<String> getSymbols(){
        return this.symbols;
    }

    //Parser Code
    private Symbol symbol(int type) {
        this.symbols.add(yytext());
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        this.symbols.add(value.toString());
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerForm(java.io.Reader in) {
      this.string = new StringBuilder();
    this.symbols = new ArrayList<>();
    this.lexicalErrors = new ArrayList<>();
    yyline = 1;
    yycolumn = 1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case SIMPLE_COMMENT: {
              yybegin(YYINITIAL);
            }  // fall though
            case 392: break;
            default:
              {
                return symbol(symForm.EOF);
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error(yytext());
            }
          // fall through
          case 93: break;
          case 2:
            { /* Ignore */
            }
          // fall through
          case 94: break;
          case 3:
            { this.string.setLength(0); yybegin(TEXT);
            }
          // fall through
          case 95: break;
          case 4:
            { this.string.setLength(0); yybegin(SIMPLE_COMMENT);
            }
          // fall through
          case 96: break;
          case 5:
            { return symbol(symForm.MODULO);
            }
          // fall through
          case 97: break;
          case 6:
            { return symbol(symForm.PARENTESIS_ABIERTO);
            }
          // fall through
          case 98: break;
          case 7:
            { return symbol(symForm.PARENTESIS_CERRADO);
            }
          // fall through
          case 99: break;
          case 8:
            { return symbol(symForm.MULTIPLICACION);
            }
          // fall through
          case 100: break;
          case 9:
            { return symbol(symForm.SUMA);
            }
          // fall through
          case 101: break;
          case 10:
            { return symbol(symForm.COMA);
            }
          // fall through
          case 102: break;
          case 11:
            { return symbol(symForm.RESTA);
            }
          // fall through
          case 103: break;
          case 12:
            { return symbol(symForm.PUNTO);
            }
          // fall through
          case 104: break;
          case 13:
            { return symbol(symForm.DIVISION);
            }
          // fall through
          case 105: break;
          case 14:
            { return symbol(symForm.NUMERO_ENTERO, Integer.parseInt(yytext()));
            }
          // fall through
          case 106: break;
          case 15:
            { return symbol(symForm.DOS_PUNTOS);
            }
          // fall through
          case 107: break;
          case 16:
            { return symbol(symForm.PUNTO_COMA);
            }
          // fall through
          case 108: break;
          case 17:
            { return symbol(symForm.MENOR);
            }
          // fall through
          case 109: break;
          case 18:
            { return symbol(symForm.IGUAL);
            }
          // fall through
          case 110: break;
          case 19:
            { return symbol(symForm.MAYOR);
            }
          // fall through
          case 111: break;
          case 20:
            { return symbol(symForm.COMODIN);
            }
          // fall through
          case 112: break;
          case 21:
            { return symbol(symForm.ID, yytext());
            }
          // fall through
          case 113: break;
          case 22:
            { return symbol(symForm.CORCHETE_ABIERTO);
            }
          // fall through
          case 114: break;
          case 23:
            { return symbol(symForm.CORCHETE_CERRADO);
            }
          // fall through
          case 115: break;
          case 24:
            { return symbol(symForm.POTENCIA);
            }
          // fall through
          case 116: break;
          case 25:
            { return symbol(symForm.LLAVE_ABIERTO);
            }
          // fall through
          case 117: break;
          case 26:
            { return symbol(symForm.LLAVE_CERRADO);
            }
          // fall through
          case 118: break;
          case 27:
            { return symbol(symForm.NOT);
            }
          // fall through
          case 119: break;
          case 28:
            { this.string.append(yytext());
            }
          // fall through
          case 120: break;
          case 29:
            { this.string.append("\n");
            }
          // fall through
          case 121: break;
          case 30:
            { System.out.println("TEXTO: " + this.string.toString().trim());
        yybegin(YYINITIAL);
        return symbol(symForm.TEXTO, this.string.toString().trim());
            }
          // fall through
          case 122: break;
          case 31:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 123: break;
          case 32:
            { return symbol(symForm.DIFERENTE);
            }
          // fall through
          case 124: break;
          case 33:
            { return symbol(symForm.AND);
            }
          // fall through
          case 125: break;
          case 34:
            { this.string.setLength(0); yybegin(MULTIPLE_COMMENT);
            }
          // fall through
          case 126: break;
          case 35:
            { return symbol(symForm.MENOR_IGUAL);
            }
          // fall through
          case 127: break;
          case 36:
            { return symbol(symForm.IGUALDAD);
            }
          // fall through
          case 128: break;
          case 37:
            { return symbol(symForm.MAYOR_IGUAL);
            }
          // fall through
          case 129: break;
          case 38:
            { return symbol(symForm.DO);
            }
          // fall through
          case 130: break;
          case 39:
            { return symbol(symForm.IF);
            }
          // fall through
          case 131: break;
          case 40:
            { return symbol(symForm.IN);
            }
          // fall through
          case 132: break;
          case 41:
            { return symbol(symForm.OR);
            }
          // fall through
          case 133: break;
          case 42:
            { System.out.println("COMENTARIO MULTILINEA: " + this.string.toString().trim());
        yybegin(YYINITIAL);
            }
          // fall through
          case 134: break;
          case 43:
            { return symbol(symForm.NUMERO_DECIMAL, Double.parseDouble(yytext()));
            }
          // fall through
          case 135: break;
          case 44:
            { return symbol(symForm.FOR);
            }
          // fall through
          case 136: break;
          case 45:
            { return symbol(symForm.RED);
            }
          // fall through
          case 137: break;
          case 46:
            { return symbol(symForm.SKY);
            }
          // fall through
          case 138: break;
          case 47:
            { this.string.setLength(0);
        this.string.append(yytext());
        this.string.deleteCharAt(0);
        return symbol(symForm.HEXADECIMAL, this.string.toString().trim());
            }
          // fall through
          case 139: break;
          case 48:
            { return symbol(symForm.BLUE);
            }
          // fall through
          case 140: break;
          case 49:
            { return symbol(symForm.ELSE);
            }
          // fall through
          case 141: break;
          case 50:
            { return symbol(symForm.LINE);
            }
          // fall through
          case 142: break;
          case 51:
            { return symbol(symForm.MONO);
            }
          // fall through
          case 143: break;
          case 52:
            { return symbol(symForm.TEXT);
            }
          // fall through
          case 144: break;
          case 53:
            { return symbol(symForm.DRAW);
            }
          // fall through
          case 145: break;
          case 54:
            { return symbol(symForm.BLACK);
            }
          // fall through
          case 146: break;
          case 55:
            { return symbol(symForm.GREEN);
            }
          // fall through
          case 147: break;
          case 56:
            { return symbol(symForm.TABLE);
            }
          // fall through
          case 148: break;
          case 57:
            { return symbol(symForm.WHILE);
            }
          // fall through
          case 149: break;
          case 58:
            { return symbol(symForm.WHITE);
            }
          // fall through
          case 150: break;
          case 59:
            { return symbol(symForm.LABEL);
            }
          // fall through
          case 151: break;
          case 60:
            { return symbol(symForm.WIDTH);
            }
          // fall through
          case 152: break;
          case 61:
            { return symbol(symForm.DOTTED);
            }
          // fall through
          case 153: break;
          case 62:
            { return symbol(symForm.DOUBLE);
            }
          // fall through
          case 154: break;
          case 63:
            { return symbol(symForm.NUMBER_POKEMON);
            }
          // fall through
          case 155: break;
          case 64:
            { return symbol(symForm.PURPLE);
            }
          // fall through
          case 156: break;
          case 65:
            { return symbol(symForm.YELLOW);
            }
          // fall through
          case 157: break;
          case 66:
            { return symbol(symForm.HEIGHT);
            }
          // fall through
          case 158: break;
          case 67:
            { return symbol(symForm.NUMBER);
            }
          // fall through
          case 159: break;
          case 68:
            { return symbol(symForm.POINT_X);
            }
          // fall through
          case 160: break;
          case 69:
            { return symbol(symForm.POINT_Y);
            }
          // fall through
          case 161: break;
          case 70:
            { return symbol(symForm.STRING);
            }
          // fall through
          case 162: break;
          case 71:
            { return symbol(symForm.STYLES);
            }
          // fall through
          case 163: break;
          case 72:
            { return symbol(symForm.COLOR);
            }
          // fall through
          case 164: break;
          case 73:
            { return symbol(symForm.CURSIVE);
            }
          // fall through
          case 165: break;
          case 74:
            { return symbol(symForm.SECTION);
            }
          // fall through
          case 166: break;
          case 75:
            { return symbol(symForm.CONTENT);
            }
          // fall through
          case 167: break;
          case 76:
            { return symbol(symForm.CORRECT);
            }
          // fall through
          case 168: break;
          case 77:
            { return symbol(symForm.OPTIONS);
            }
          // fall through
          case 169: break;
          case 78:
            { return symbol(symForm.SPECIAL);
            }
          // fall through
          case 170: break;
          case 79:
            { return symbol(symForm.BORDER);
            }
          // fall through
          case 171: break;
          case 80:
            { return symbol(symForm.VERTICAL);
            }
          // fall through
          case 172: break;
          case 81:
            { return symbol(symForm.ELEMENTS);
            }
          // fall through
          case 173: break;
          case 82:
            { return symbol(symForm.HORIZONTAL);
            }
          // fall through
          case 174: break;
          case 83:
            { return symbol(symForm.SANS_SERIF);
            }
          // fall through
          case 175: break;
          case 84:
            { return symbol(symForm.TEXT_SIZE);
            }
          // fall through
          case 176: break;
          case 85:
            { return symbol(symForm.ORIENTATION);
            }
          // fall through
          case 177: break;
          case 86:
            { return symbol(symForm.FONT_FAMILY);
            }
          // fall through
          case 178: break;
          case 87:
            { return symbol(symForm.DROP_QUESTION);
            }
          // fall through
          case 179: break;
          case 88:
            { return symbol(symForm.OPEN_QUESTION);
            }
          // fall through
          case 180: break;
          case 89:
            { return symbol(symForm.SELECT_QUESTION);
            }
          // fall through
          case 181: break;
          case 90:
            { return symbol(symForm.MULTIPLE_QUESTION);
            }
          // fall through
          case 182: break;
          case 91:
            { return symbol(symForm.BACKGROUND_COLOR);
            }
          // fall through
          case 183: break;
          case 92:
            { return symbol(symForm.WHO_IS_THAT_POKEMON);
            }
          // fall through
          case 184: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
