
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyecto1_compi1_ps26.domain.analyzers.form_creation;

/** CUP generated class containing symbol constants. */
public class symForm {
  /* terminals */
  public static final int HORIZONTAL = 47;
  public static final int CORCHETE_CERRADO = 22;
  public static final int SELECT_QUESTION = 36;
  public static final int HEXADECIMAL = 82;
  public static final int TEXT_SIZE = 70;
  public static final int DIVISION = 5;
  public static final int MENOR_IGUAL = 15;
  public static final int TABLE = 33;
  public static final int POTENCIA = 6;
  public static final int CORCHETE_ABIERTO = 21;
  public static final int MAYOR = 12;
  public static final int NUMBER_POKEMON = 79;
  public static final int TEXTO = 84;
  public static final int SANS_SERIF = 49;
  public static final int DROP_QUESTION = 35;
  public static final int NUMERO_ENTERO = 81;
  public static final int SPECIAL = 30;
  public static final int BLUE = 39;
  public static final int YELLOW = 43;
  public static final int DIFERENTE = 11;
  public static final int ELEMENTS = 61;
  public static final int DRAW = 57;
  public static final int WHITE = 45;
  public static final int OPEN_QUESTION = 31;
  public static final int BLACK = 44;
  public static final int DOUBLE = 53;
  public static final int NUMERO_DECIMAL = 80;
  public static final int BACKGROUND_COLOR = 68;
  public static final int NOT = 18;
  public static final int TEXT = 34;
  public static final int DOS_PUNTOS = 23;
  public static final int PURPLE = 41;
  public static final int WIDTH = 54;
  public static final int PUNTO_COMA = 27;
  public static final int IGUALDAD = 10;
  public static final int STYLES = 62;
  public static final int NUMBER = 28;
  public static final int COMA = 20;
  public static final int MODULO = 7;
  public static final int CURSIVE = 50;
  public static final int MONO = 48;
  public static final int LLAVE_CERRADO = 26;
  public static final int IGUAL = 19;
  public static final int WHILE = 74;
  public static final int FOR = 76;
  public static final int DO = 75;
  public static final int COMODIN = 24;
  public static final int ORIENTATION = 60;
  public static final int ELSE = 73;
  public static final int MULTIPLE_QUESTION = 37;
  public static final int MENOR = 13;
  public static final int LLAVE_ABIERTO = 25;
  public static final int CORRECT = 65;
  public static final int CONTENT = 63;
  public static final int EOF = 0;
  public static final int PUNTO = 78;
  public static final int VERTICAL = 46;
  public static final int SUMA = 2;
  public static final int LINE = 51;
  public static final int LABEL = 56;
  public static final int IN = 77;
  public static final int OR = 17;
  public static final int SKY = 42;
  public static final int error = 1;
  public static final int RESTA = 3;
  public static final int POINT_Y = 59;
  public static final int IF = 72;
  public static final int POINT_X = 58;
  public static final int PARENTESIS_CERRADO = 9;
  public static final int ID = 83;
  public static final int DOTTED = 52;
  public static final int COLOR = 67;
  public static final int MULTIPLICACION = 4;
  public static final int BORDER = 71;
  public static final int HEIGHT = 55;
  public static final int RED = 38;
  public static final int FONT_FAMILY = 69;
  public static final int STRING = 29;
  public static final int PARENTESIS_ABIERTO = 8;
  public static final int OPTIONS = 64;
  public static final int AND = 16;
  public static final int WHO_IS_THAT_POKEMON = 66;
  public static final int MAYOR_IGUAL = 14;
  public static final int SECTION = 32;
  public static final int GREEN = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "IGUALDAD",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "IGUAL",
  "COMA",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "DOS_PUNTOS",
  "COMODIN",
  "LLAVE_ABIERTO",
  "LLAVE_CERRADO",
  "PUNTO_COMA",
  "NUMBER",
  "STRING",
  "SPECIAL",
  "OPEN_QUESTION",
  "SECTION",
  "TABLE",
  "TEXT",
  "DROP_QUESTION",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "RED",
  "BLUE",
  "GREEN",
  "PURPLE",
  "SKY",
  "YELLOW",
  "BLACK",
  "WHITE",
  "VERTICAL",
  "HORIZONTAL",
  "MONO",
  "SANS_SERIF",
  "CURSIVE",
  "LINE",
  "DOTTED",
  "DOUBLE",
  "WIDTH",
  "HEIGHT",
  "LABEL",
  "DRAW",
  "POINT_X",
  "POINT_Y",
  "ORIENTATION",
  "ELEMENTS",
  "STYLES",
  "CONTENT",
  "OPTIONS",
  "CORRECT",
  "WHO_IS_THAT_POKEMON",
  "COLOR",
  "BACKGROUND_COLOR",
  "FONT_FAMILY",
  "TEXT_SIZE",
  "BORDER",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "IN",
  "PUNTO",
  "NUMBER_POKEMON",
  "NUMERO_DECIMAL",
  "NUMERO_ENTERO",
  "HEXADECIMAL",
  "ID",
  "TEXTO"
  };
}

